registerAlgebraChapter({
  id: "ch4",
  icon: "4",
  title: "第四章 矩阵",
  subtitle: "教材 §1—§7",
  summary:
    "本章严格按教材 §1 到 §7 的顺序组织：先建立矩阵概念，再讨论运算、矩阵乘积的行列式与秩、逆、分块、初等矩阵，以及分块乘法中的初等变换与应用。现有交互和例题按对应教材节重新落位。",
  sections: [
    {
      id: "matrix-language",
      number: "§1",
      textbookSection: "矩阵概念的一些背景",
      title: "矩阵概念的一些背景",
      navTitle: "矩阵概念背景",
      question: `矩阵为什么会出现？它除了是一张数字表格，还能记录什么？`,
      goal: "从矩阵的背景与基本记法出发，建立“矩阵可以记录线性映射在选定基下的作用”这一核心视角。",
      tags: ["矩阵背景", "行列与阶", "基向量"],
      intro:
        "矩阵最初服务于方程组、数据排列和计算规则，但它更深的作用是记录线性关系。逐列地看，矩阵记录标准基向量的去向；整体地看，它记录整个空间怎样拉伸、旋转、剪切或压缩。",
      concepts: [
        { label: "矩阵", text: "矩阵是按行和列排列的数表；它的行数和列数共同确定矩阵的阶。" },
        { label: "列向量", text: "在线性映射视角下，矩阵的第 j 列就是第 j 个标准基向量经过变换后的坐标。" },
        { label: "线性性", text: "知道基向量的去向，就知道所有向量的去向，因为线性组合关系会被保留。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章",
        page: "",
        items: ["矩阵概念的背景", "矩阵的行、列与阶", "矩阵的基本记法", "矩阵作为线性关系的记录"],
      },
      visual: {
        type: "transform",
        title: "交互图：矩阵怎样改变网格",
        description: "拖动矩阵元素，观察基向量和整张网格同步变化。",
        prompts: [
          "先固定原始网格和两个标准基向量。",
          "拖动四个矩阵元素，让网格实时变形。",
          `观察两列向量的变化，再回到公式 ${texInline("A(x,y)^T=xAe_1+yAe_2")}。`,
        ],
      },
      example: {
        title: "例题：从列向量读出变换",
        question: `设 ${texInline("A=\\begin{bmatrix}2&1\\\\0&1\\end{bmatrix}")}。不用逐点代入，说明它对平面网格的大致作用。`,
        steps: [
          `第一列是 ${texInline("(2,0)^T")}，所以 ${texInline("e_1")} 被拉到 x 轴正方向并放大 2 倍。`,
          `第二列是 ${texInline("(1,1)^T")}，所以 ${texInline("e_2")} 被送到斜向量。`,
          "水平方向被拉长，竖直方向同时向右偏移，整体表现为横向拉伸和剪切。",
        ],
      },
      quiz: [
        {
          question: `矩阵 ${texInline("A")} 的第 j 列在变换视角下表示什么？`,
          answer: `它表示标准基向量 ${texInline("e_j")} 经过 ${texInline("A")} 后得到的坐标，即 ${texInline("Ae_j")}。`,
        },
        {
          question: "为什么知道基向量的去向就能知道所有向量的去向？",
          answer: "任意向量都可写成基向量的线性组合；线性映射保持线性组合关系。",
        },
      ],
      summary: ["矩阵首先是一种结构化记录。", "从列向量读矩阵，可以把数字表格还原为线性映射。"],
      exercises: ["调节交互图中的 b，让竖直网格线逐渐倾斜，观察剪切量怎样变化。"],
    },
    {
      id: "matrix-operations",
      number: "§2",
      textbookSection: "矩阵的运算",
      title: "矩阵的运算",
      navTitle: "矩阵的运算",
      question: "矩阵为什么能相加、数乘和相乘？这些规则分别在表达什么结构？",
      goal: "把加法、数乘理解成同类记录的叠加与缩放，并把矩阵乘法理解成线性变换的复合。",
      tags: ["加法与数乘", "矩阵乘法", "复合变换"],
      intro:
        "矩阵加法和数乘让同型矩阵像向量一样形成线性组合；矩阵乘法则不只是逐项计算，而是在压缩两个线性变换的复合过程。",
      video: {
        title: "矩阵乘法为什么对应复合",
        duration: "约 2 分钟",
        script: [
          "先让一个向量经过 B，得到中间结果。",
          "再把中间结果交给 A，得到最终结果。",
          "把两个动作合成一次动作，记作 AB。",
          "回到坐标，解释为什么右边的矩阵先作用。",
        ],
      },
      concepts: [
        { label: "同型相加", text: "只有尺寸相同的矩阵才能逐项相加，这对应同一类输入输出记录的叠加。" },
        { label: "数乘", text: "把矩阵所有列向量同时缩放，也就是把记录的变换强度整体缩放。" },
        { label: "矩阵乘法", text: `${texInline("ABx")} 表示 ${texInline("B")} 先作用在 ${texInline("x")} 上，再由 ${texInline("A")} 作用到 ${texInline("Bx")} 上。` },
        { label: "行列配对", text: "行乘列是在计算输出的一个坐标如何由输入基向量的响应组合出来。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章",
        page: "",
        items: ["矩阵的加法与数乘", "矩阵乘法", "转置与基本运算性质"],
      },
      visual: {
        type: "multiply",
        title: "交互图：AB 是先 B 后 A",
        description: "切换复合、列向量与行列公式三个视角，比较同一件事的不同表达。",
        task: `先选“复合”观察 ${texInline("x\\to Bx\\to A(Bx)")}，再切到“看列”，说明 ${texInline("AB")} 的每一列为什么来自 ${texInline("A")} 作用到 ${texInline("B")} 的对应列。`,
        prompts: [
          `第一步：向量 ${texInline("x")} 经过 ${texInline("B")} 到达中间位置。`,
          `第二步：中间向量再经过 ${texInline("A")} 到达最终位置。`,
          `第三步：把整个过程压缩成 ${texInline("ABx")}，并观察 ${texInline("AB")} 的列。`,
        ],
      },
      example: {
        title: "例题：比较 AB 与 BA",
        question: "设 A 表示横向拉伸，B 表示剪切。为什么先剪切再拉伸，通常不同于先拉伸再剪切？",
        steps: [
          `取 ${texInline("A=\\begin{bmatrix}2&0\\\\0&1\\end{bmatrix}")}，${texInline("B=\\begin{bmatrix}1&1\\\\0&1\\end{bmatrix}")}。`,
          `${texInline("AB=\\begin{bmatrix}2&2\\\\0&1\\end{bmatrix}")}，${texInline("BA=\\begin{bmatrix}2&1\\\\0&1\\end{bmatrix}")}。`,
          "右上角不同，说明剪切量与拉伸顺序发生耦合；第二个变换面对的是第一个变换已经改变后的图形。",
        ],
      },
      quiz: [
        {
          question: `判断：${texInline("ABx")} 中，${texInline("A")} 先作用在 ${texInline("x")} 上。`,
          answer: "错。右边的矩阵先作用，所以先得到 Bx，再由 A 作用到 Bx。",
        },
        {
          question: `${texInline("AB")} 的第 j 列可以怎样理解？`,
          answer: `${texInline("AB")} 的第 j 列是 ${texInline("A")} 作用到 ${texInline("B")} 的第 j 列后的结果。`,
        },
        {
          question: `怎样把 ${texInline("\\begin{bmatrix}3&-1\\\\2&0\\end{bmatrix}")} 写成 2 阶基本矩阵的线性组合？`,
          answer: `${texInline("3E_{11}-E_{12}+2E_{21}+0E_{22}")}。`,
        },
      ],
      summary: ["同型矩阵可以相加和数乘。", "矩阵乘法的核心是复合：右边先作用，左边后作用。"],
      exercises: ["用两个简单 2 阶矩阵再找一个 AB 与 BA 不相等的例子。"],
    },
    {
      id: "matrix-product-determinant-rank",
      number: "§3",
      textbookSection: "矩阵乘积的行列式与秩",
      title: "矩阵乘积的行列式与秩",
      navTitle: "乘积的行列式与秩",
      question: "矩阵相乘以后，面积缩放和有效维度会怎样变化？秩到底在数什么？",
      goal: "把行列式理解为面积或体积的缩放因子，把秩理解为矩阵真正保留下来的有效维度。",
      tags: ["行列式", "秩", "有效维度"],
      intro:
        "矩阵乘积会连续施加两个变换，因此面积或体积的缩放因子相乘；秩则描述变换后仍然保留下来的独立方向数。",
      concepts: [
        { label: "乘积行列式", text: `${texInline("\\det(AB)=\\det(A)\\det(B)")}，连续变换的面积或体积缩放因子会相乘。` },
        { label: "秩", text: "秩描述矩阵作为变换时保留下来的有效维度。" },
        { label: "列秩", text: "列向量张成空间的维数，描述输出能到达的范围。" },
        { label: "乘积与秩", text: `${texInline("\\operatorname{rank}(AB)\\leq\\min\\{\\operatorname{rank}(A),\\operatorname{rank}(B)\\}")}；复合不会凭空创造独立方向。` },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章",
        page: "",
        items: ["矩阵乘积的行列式", "矩阵的秩", "乘积与秩的关系"],
      },
      visual: {
        type: "rank",
        title: "交互图：秩是保留下来的维度",
        description: "比较列向量张成平面和坍缩成直线时的差别。",
        prompts: [
          "从列向量出发，观察它们张成平面还是只张成直线。",
          "把“独立方向的数量”与秩联系起来。",
          "再回到乘积，理解复合不会增加有效维度。",
        ],
      },
      example: {
        title: "例题：从列关系判断秩",
        question: `矩阵 ${texInline("A")} 的三列满足 ${texInline("c_3=2c_1-c_2")}，且 ${texInline("c_1,c_2")} 线性无关。${texInline("\\operatorname{rank}(A)")} 是多少？`,
        steps: [
          "第三列已经由前两列线性表示，所以不提供新方向。",
          `前两列 ${texInline("c_1,c_2")} 线性无关，所以至少有两个独立方向。`,
          `列空间维数正好是 ${texInline("2")}，因此 ${texInline("\\operatorname{rank}(A)=2")}。`,
        ],
      },
      quiz: [
        {
          question: `若 ${texInline("\\det(A)\\ne0")}，n 阶矩阵 ${texInline("A")} 的秩是多少？`,
          answer: "秩为 n。非零行列式意味着变换没有把空间压到低维对象。",
        },
        {
          question: "为什么复合变换通常不能增加秩？",
          answer: "后一个变换只能继续处理前一个变换已经留下的输出方向，不能恢复前一步已经丢失的独立方向。",
        },
      ],
      summary: ["行列式描述缩放，秩描述有效维度。", "矩阵乘积对应复合，因此行列式相乘，秩不会凭空增加。"],
      exercises: ["构造一个 3 列矩阵，使三列都非零但秩为 1。"],
    },
    {
      id: "matrix-inverse",
      number: "§4",
      textbookSection: "矩阵的逆",
      title: "矩阵的逆",
      navTitle: "矩阵的逆",
      question: "一个矩阵什么时候能把输入完整恢复出来？几何图像上会出现什么信号？",
      goal: "把可逆理解成变换没有压扁信息，并串起逆矩阵、行列式、秩与方程组唯一解。",
      tags: ["可逆", "信息不丢失", "等价条件"],
      intro: `矩阵可逆意味着它没有让不同输入不可分辨：网格没有被压扁，列向量张成全空间，秩满，方程 ${texInline("Ax=b")} 对每个 ${texInline("b")} 有唯一解。`,
      concepts: [
        { label: "逆矩阵", text: `${texInline("A^{-1}A=AA^{-1}=I")}；逆矩阵把变换后的结果送回原来的输入。` },
        { label: "几何直觉", text: "可逆意味着空间没有被压到低维对象上。" },
        { label: "代数条件", text: "n 阶矩阵可逆等价于秩为 n，也等价于行最简形为 I。" },
        { label: "方程组视角", text: `${texInline("Ax=b")} 对任意 ${texInline("b")} 有唯一解，说明 ${texInline("A")} 能完整追踪输入。` },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章",
        page: "",
        items: ["逆矩阵", "可逆矩阵的判定", "求逆与相关性质"],
      },
      visual: {
        type: "slot",
        label: "可逆性对照",
        title: "图示：可逆与坍缩",
        description: "并排比较可逆与不可逆：左侧网格仍铺满平面，右侧网格坍缩成直线。",
        text: `观察 ${texInline("\\det A")} 接近 0 时网格面积怎样变化，再把几何坍缩与 ${texInline("\\operatorname{rank}(A)<n")} 联系起来。`,
      },
      example: {
        title: "例题：不用求逆判断可逆",
        question: "设 A 的三列向量线性相关。A 可能可逆吗？为什么？",
        steps: [
          `三列线性相关说明列空间维数小于 ${texInline("3")}。`,
          `于是 ${texInline("\\operatorname{rank}(A)<3")}。`,
          "对 3 阶矩阵来说，满秩才可能可逆；几何上看，A 至少让某个非零方向丢失信息。",
        ],
      },
      summary: ["可逆等价于满秩。", "几何上，可逆变换不会把空间压到低维对象。"],
      exercises: [`用秩判断 ${texInline("\\begin{bmatrix}1&2&3\\\\2&4&6\\\\0&1&1\\end{bmatrix}")} 是否可逆。`],
    },
    {
      id: "block-matrices",
      number: "§5",
      textbookSection: "矩阵的分块",
      title: "矩阵的分块",
      navTitle: "矩阵的分块",
      question: "为什么把大矩阵切成小块以后，计算会更清楚？分块在表达什么结构？",
      goal: "把大矩阵拆成有意义的小矩阵，让计算服务于结构。",
      tags: ["分块", "块乘法", "空间分解"],
      intro:
        "分块矩阵是组织复杂信息的工具。当线性映射尊重某种分解时，矩阵会呈现更清楚的结构；块不是装饰，而是在标出问题内部相互关联或相互独立的部分。",
      concepts: [
        { label: "分块", text: "按照行和列的划分，把一个大矩阵看成若干尺寸匹配的小矩阵。" },
        { label: "块乘法", text: "只要尺寸匹配，块可以像元素一样参与乘法。" },
        { label: "块对角", text: "不同子空间互不耦合时，矩阵会呈现块对角结构。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章",
        page: "",
        items: ["矩阵的分块", "分块运算", "块对角矩阵"],
      },
      visual: {
        type: "block",
        title: "图示：把大矩阵看成小系统",
        description: "分块让输入、输出和子结构更清楚。",
        prompts: [
          "把一个大矩阵切成四块，并标出每块的输入输出含义。",
          "演示块乘法时，只高亮真正发生配对的块。",
          "用块对角矩阵展示两个子系统互不干扰的情况。",
        ],
      },
      example: {
        title: "例题：块对角矩阵的逆",
        question: `若 ${texInline("A,D")} 都可逆，为什么 ${texInline("\\operatorname{diag}(A,D)")} 的逆是 ${texInline("\\operatorname{diag}(A^{-1},D^{-1})")}？`,
        steps: [
          "块对角矩阵表示两个部分互不混合。",
          `${texInline("\\operatorname{diag}(A,D)\\operatorname{diag}(A^{-1},D^{-1})=\\operatorname{diag}(AA^{-1},DD^{-1})")}。`,
          `${texInline("AA^{-1}=I")} 且 ${texInline("DD^{-1}=I")}，所以乘积为 ${texInline("\\operatorname{diag}(I,I)")}。`,
        ],
      },
      summary: ["分块让结构先被看见。", "块对角矩阵可以按子系统分别处理。"],
      exercises: [`验证 ${texInline("\\begin{bmatrix}A&0\\\\0&D\\end{bmatrix}\\begin{bmatrix}B&0\\\\0&E\\end{bmatrix}=\\begin{bmatrix}AB&0\\\\0&DE\\end{bmatrix}")}。`],
    },
    {
      id: "elementary-matrices",
      number: "§6",
      textbookSection: "初等矩阵",
      title: "初等矩阵",
      navTitle: "初等矩阵",
      question: "一次初等变换怎样写成左乘一个矩阵？为什么初等变换都可逆？",
      goal: "把初等行变换看成左乘初等矩阵，把初等列变换看成右乘初等矩阵。",
      tags: ["初等变换", "左乘右乘", "可逆操作"],
      intro:
        "初等矩阵把消元法和矩阵乘法连起来。一次初等行操作就是一个可逆的线性操作；连续行操作也可以压缩为一串初等矩阵的乘积。",
      concepts: [
        { label: "换行", text: "交换两行对应左乘一个置换矩阵。" },
        { label: "倍乘", text: "某一行乘非零常数，对应沿某个坐标方向缩放。" },
        { label: "倍加", text: "一行加上另一行的倍数，对应剪切型操作。" },
        { label: "左乘与右乘", text: "左乘初等矩阵对应行变换；右乘初等矩阵对应列变换。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章",
        page: "",
        items: ["初等行变换与初等列变换", "初等矩阵", "初等矩阵的逆"],
      },
      visual: {
        type: "slot",
        label: "消元演示",
        title: "图示：行变换怎样变成左乘",
        description: `左侧显示矩阵，右侧显示 ${texInline("E_k\\cdots E_2E_1A")}，每次行操作同步高亮对应的初等矩阵。`,
        text: `同一个行操作施加到单位矩阵上，就得到对应的初等矩阵；连续消元可以写成 ${texInline("E_k\\cdots E_2E_1A")}。`,
      },
      example: {
        title: "例题：把行变换写成左乘",
        question: `对 ${texInline("2\\times2")} 矩阵 ${texInline("A")} 执行 ${texInline("R_2\\leftarrow R_2-3R_1")}。对应的初等矩阵是什么？`,
        steps: [
          `对单位矩阵 ${texInline("I")} 做同样的行变换。`,
          `得到 ${texInline("E=\\begin{bmatrix}1&0\\\\-3&1\\end{bmatrix}")}。`,
          `因此变换后的矩阵就是 ${texInline("EA")}；找初等矩阵时，把同样操作施加到单位矩阵上。`,
        ],
      },
      summary: ["初等行变换对应左乘初等矩阵。", "初等矩阵可逆，逆矩阵对应反向初等变换。"],
      exercises: [`写出 ${texInline("R_1\\leftarrow R_1+2R_2")} 对应的 2 阶初等矩阵。`],
    },
    {
      id: "block-elementary-applications",
      number: "§7",
      textbookSection: "分块乘法的初等变换及应用举例",
      title: "分块乘法的初等变换及应用举例",
      navTitle: "分块初等变换与应用",
      question: "怎样把初等变换推广到分块矩阵，并让分块计算真正服务于具体问题？",
      goal: "在课程结构中为教材 §7 留出准确位置；后续将依据教材具体例题补足分块初等变换与应用。",
      tags: ["分块初等变换", "应用举例", "待补足"],
      intro:
        "这一节已经按教材目录落位。现阶段不凭空补写教材的具体应用例题；待你提供本节正文、例题或页码后，再把分块初等变换的过程和应用做成适当的步进推导。",
      concepts: [
        { label: "分块初等变换", text: "把适当尺寸的矩阵块作为操作对象，前提仍然是块的尺寸与乘法方向匹配。" },
        { label: "应用举例", text: "本节应以教材给出的具体问题为中心，而不是为了完整目录而虚构一个应用。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章",
        page: "",
        items: ["分块乘法的初等变换", "应用举例", "待依据教材正文补足"],
      },
      summary: ["第四章的七个教材节现在都已有准确位置。", "本节保留为空间，等待依据教材具体内容继续展开。"],
    },
  ],
});
