registerAlgebraChapter({
  id: "ch4",
  icon: "4",
  title: "第四章 矩阵",
  subtitle: "矩阵",
  summary:
    "本章围绕一条主线展开：矩阵记录线性映射在基下的作用。乘法对应复合，初等矩阵对应可逆操作，秩对应保留下来的有效维度。",
  sections: [
    {
      id: "matrix-language",
      number: "4.1",
      textbookSection: "§4.1",
      title: "矩阵作为线性映射的记录",
      navTitle: "矩阵与线性映射",
      question: `矩阵 ${texInline("A")} 的每一列在记录什么？为什么知道基向量的去向，就能知道所有向量的去向？`,
      goal: "把矩阵从数字表格还原成输入向量怎样被送到输出向量的记录。",
      tags: ["二维网格", "基向量", "交互优先"],
      intro:
        "这一节先建立一个核心直觉：一列一列地看矩阵，看到的是标准基向量的去向；整体地看矩阵，看到的是整个空间怎样拉伸、旋转、剪切或压缩。",
      concepts: [
        { label: "列向量", text: "矩阵的第 j 列就是第 j 个标准基向量经过变换后的坐标。" },
        { label: "线性性", text: "知道基向量的去向，就知道所有向量的去向，因为线性组合关系会被保留。" },
        { label: "坐标语言", text: "矩阵记录选定基下的变换效果，帮助我们用坐标描述线性映射。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章 矩阵",
        page: "",
        items: ["矩阵的定义", "矩阵与线性映射的坐标表示", "列向量视角"],
      },
      visual: {
        type: "transform",
        title: "交互图：矩阵怎样改变网格",
        description: "拖动矩阵元素，观察基向量和整张网格同步变化。",
        prompts: [
          "先固定原始网格和两个标准基向量。",
          "拖动四个矩阵元素，让网格实时变形。",
          `观察两列向量的变化，再回到公式 ${texInline("A(x,y)^T=xAe_1+yAe_2")}。`,
        ],
      },
      example: {
        title: "例题 4.1：从列向量读出变换",
        question: `设 ${texInline("A=\\begin{bmatrix}2&1\\\\0&1\\end{bmatrix}")}。不用逐点代入，说明它对平面网格的大致作用。`,
        steps: [
          `第一列是 ${texInline("(2,0)^T")}，所以 ${texInline("e_1")} 被拉到 x 轴正方向并放大 2 倍。`,
          `第二列是 ${texInline("(1,1)^T")}，所以 ${texInline("e_2")} 被送到斜向量。`,
          "水平方向被拉长，竖直方向同时向右偏移，整体表现为横向拉伸和剪切。",
        ],
      },
      summary: ["矩阵可以从列向量读起。", "基向量的去向决定整个线性映射。"],
      exercises: ["调节交互图中的 b，让竖直网格线逐渐倾斜，观察剪切量怎样变化。"],
    },
    {
      id: "matrix-operations",
      number: "4.2",
      textbookSection: "§4.2",
      title: "矩阵加法、数乘与线性组合",
      navTitle: "矩阵运算",
      question: "矩阵为什么能像向量一样相加和数乘？这些运算保留了什么结构？",
      goal: "把矩阵运算理解成变换记录之间的叠加与缩放。",
      tags: ["运算规则", "线性组合", "结构感"],
      intro:
        "矩阵加法和数乘承担语言桥的作用：矩阵集合本身可以形成线性空间，矩阵可以像向量一样被加、被数乘、被线性组合。",
      concepts: [
        { label: "同型相加", text: "只有尺寸相同的矩阵才能逐项相加，这对应同一类输入输出记录的叠加。" },
        { label: "数乘", text: "把矩阵所有列向量同时缩放，也就是把记录的变换强度整体缩放。" },
        { label: "线性组合", text: "若干基本矩阵可以拼出更复杂的矩阵，这会为矩阵空间做铺垫。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章 矩阵",
        page: "",
        items: ["矩阵加法", "数量乘法", "矩阵空间的线性组合"],
      },
      visual: {
        type: "slot",
        label: "运算图示",
        title: "图示：列向量怎样相加",
        description: "两组列向量逐渐叠加，最后落到对应元素相加的公式。",
        text: `用两组颜色区分 ${texInline("A")} 与 ${texInline("B")} 的列向量，先看列向量叠加，再回到矩阵同位置相加。`,
        prompts: [
          `用两组颜色区分 ${texInline("A")} 与 ${texInline("B")} 的列向量。`,
          "先展示列向量叠加，再回到矩阵同位置相加。",
          `最后引出矩阵空间 ${texInline("M_{m\\times n}(F)")} 的线性组合视角。`,
        ],
      },
      example: {
        title: "例题 4.2：判断线性组合",
        question: `设 ${texInline("E_{11},E_{12},E_{21},E_{22}")} 是 ${texInline("2\\times2")} 基本矩阵。怎样表示矩阵 ${texInline("\\begin{bmatrix}3&-1\\\\2&0\\end{bmatrix}")}？`,
        steps: [
          "按位置把矩阵拆成四个基本矩阵的倍数。",
          `${texInline("\\begin{bmatrix}3&-1\\\\2&0\\end{bmatrix}=3E_{11}-E_{12}+2E_{21}+0E_{22}")}。`,
          "这个例子说明矩阵空间的基与坐标和普通向量空间的坐标遵循同一套语言。",
        ],
      },
      summary: ["矩阵同型时才能相加。", "基本矩阵给矩阵空间提供了自然坐标。"],
      exercises: ["把任意一个 2 阶矩阵写成四个基本矩阵的线性组合。"],
    },
    {
      id: "matrix-multiplication",
      number: "4.3",
      textbookSection: "§4.3",
      title: "矩阵乘法：复合、顺序与行列配对",
      navTitle: "矩阵乘法与复合",
      question: `为什么 ${texInline("AB")} 表示先做 ${texInline("B")} 再做 ${texInline("A")}？行乘列公式从哪里来？`,
      goal: `把 ${texInline("AB")} 理解成先做 ${texInline("B")} 再做 ${texInline("A")}，同时解释行乘列公式的含义。`,
      tags: ["复合变换", "顺序敏感", "核心动画"],
      intro:
        "矩阵乘法适合从线性变换复合进入。先看空间动作的先后顺序，再把这个过程压缩成坐标公式，顺序敏感就会变得自然。",
      video: {
        title: "矩阵乘法为什么对应复合",
        duration: "约 2 分钟",
        script: [
          "先让一个向量经过 B，得到中间结果。",
          "再把中间结果交给 A，得到最终结果。",
          "把两个动作合成一次动作，记作 AB。",
          "回到坐标，解释为什么右边的矩阵先作用。",
        ],
      },
      concepts: [
        { label: "复合", text: `${texInline("ABx")} 表示 ${texInline("B")} 先作用在 ${texInline("x")} 上，${texInline("A")} 再作用在 ${texInline("Bx")} 上。` },
        { label: "列的意义", text: `${texInline("AB")} 的第 ${texInline("j")} 列等于 ${texInline("A")} 作用到 ${texInline("B")} 的第 ${texInline("j")} 列。` },
        { label: "行列公式", text: "行乘列把“线性组合后再取坐标”的过程写成数字。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章 矩阵",
        page: "",
        items: ["矩阵乘法定义", "矩阵乘法结合律", "单位矩阵"],
      },
      visual: {
        type: "multiply",
        title: "交互图：AB 是先 B 后 A",
        description: "切换视角，比较复合、列向量与行列公式。",
        task: `先选“复合”观察 ${texInline("x\\to Bx\\to A(Bx)")}，再切到“看列”，说明 ${texInline("AB")} 的每一列为什么来自 ${texInline("A")} 作用到 ${texInline("B")} 的对应列。`,
        prompts: [
          `第一步：向量 ${texInline("x")} 经过 ${texInline("B")} 到达中间位置。`,
          `第二步：中间向量再经过 ${texInline("A")} 到达最终位置。`,
          `第三步：把整个过程压缩成 ${texInline("ABx")}，并观察 ${texInline("AB")} 的列。`,
        ],
      },
      example: {
        title: "例题 4.3：比较 AB 与 BA",
        question: "设 A 表示横向拉伸，B 表示剪切。为什么先剪切再拉伸，通常不同于先拉伸再剪切？",
        steps: [
          `取 ${texInline("A=\\begin{bmatrix}2&0\\\\0&1\\end{bmatrix}")}，${texInline("B=\\begin{bmatrix}1&1\\\\0&1\\end{bmatrix}")}。`,
          `${texInline("AB=\\begin{bmatrix}2&2\\\\0&1\\end{bmatrix}")}，${texInline("BA=\\begin{bmatrix}2&1\\\\0&1\\end{bmatrix}")}。`,
          "右上角不同，说明剪切量与拉伸顺序发生耦合。第二个变换面对的是第一个变换已经改变后的图形。",
        ],
      },
      quiz: [
        {
          question: `判断：${texInline("ABx")} 中，${texInline("A")} 先作用在 ${texInline("x")} 上。`,
          answer: "错。右边的矩阵先作用，所以先得到 Bx，再由 A 作用到 Bx。",
        },
        {
          question: `${texInline("AB")} 的第 ${texInline("j")} 列可以怎样理解？`,
          answer: `${texInline("AB")} 的第 ${texInline("j")} 列是 ${texInline("A")} 作用到 ${texInline("B")} 的第 ${texInline("j")} 列后的结果。`,
        },
        {
          question: "为什么一般不能把 AB 和 BA 互换？",
          answer: "两个变换的先后顺序会改变第二个变换面对的对象，因此最终效果通常不同。",
        },
      ],
      summary: ["矩阵乘法的核心是复合。", "右边的矩阵先作用，左边的矩阵后作用。"],
      exercises: ["用两个简单 2 阶矩阵再找一个 AB 与 BA 不相等的例子。"],
    },
    {
      id: "elementary-matrices",
      number: "4.4",
      textbookSection: "§4.4",
      title: "初等变换与初等矩阵",
      navTitle: "初等矩阵",
      question: "一次行变换怎样写成左乘一个矩阵？为什么初等行变换都可逆？",
      goal: "把行变换看成左乘初等矩阵，把列变换看成右乘初等矩阵。",
      tags: ["消元", "行空间", "可逆操作"],
      intro:
        "初等矩阵把消元法和矩阵乘法连起来。一次行操作就是一个可逆的线性操作，连续行操作可以写成一个矩阵乘积。",
      concepts: [
        { label: "换行", text: "交换两行对应左乘一个置换矩阵。" },
        { label: "倍乘", text: "某一行乘非零常数，对应沿某个坐标方向缩放。" },
        { label: "倍加", text: "一行加上另一行的倍数，对应剪切型操作。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章 矩阵",
        page: "",
        items: ["初等行变换", "初等矩阵", "左乘与右乘"],
      },
      visual: {
        type: "slot",
        label: "消元演示",
        title: "图示：行变换怎样变成左乘",
        description: `左侧显示矩阵，右侧显示 ${texInline("E_k\\cdots E_2E_1A")}，每次行操作同步高亮对应的初等矩阵。`,
        text: `同一个行操作施加到单位矩阵上，就得到对应的初等矩阵。连续消元可以写成 ${texInline("E_k\\cdots E_2E_1A")}。`,
        prompts: [
          "先演示三种初等行变换。",
          `把每一步写成 ${texInline("E_iA")}。`,
          `把连续消元合并为 ${texInline("EA=R")} 的形式，为秩和可逆性做铺垫。`,
        ],
      },
      example: {
        title: "例题 4.4：把行变换写成左乘",
        question: `对 ${texInline("2\\times2")} 矩阵 ${texInline("A")} 执行 ${texInline("R_2\\leftarrow R_2-3R_1")}。对应的初等矩阵是什么？`,
        steps: [
          `对单位矩阵 ${texInline("I")} 做同样的行变换。`,
          `得到 ${texInline("E=\\begin{bmatrix}1&0\\\\-3&1\\end{bmatrix}")}。`,
          `因此变换后的矩阵就是 ${texInline("EA")}。找初等矩阵时，把同样操作施加到单位矩阵上。`,
        ],
      },
      summary: ["初等行变换对应左乘初等矩阵。", "初等矩阵可逆，逆矩阵对应反向行变换。"],
      exercises: [`写出 ${texInline("R_1\\leftarrow R_1+2R_2")} 对应的 2 阶初等矩阵。`],
    },
    {
      id: "invertible-matrices",
      number: "4.5",
      textbookSection: "§4.5",
      title: "可逆矩阵与等价条件",
      navTitle: "可逆矩阵",
      question: "一个矩阵什么时候能把输入完整恢复出来？几何图像上会出现什么信号？",
      goal: "把可逆理解成变换没有压扁信息，并串起行列式、秩、方程组唯一解。",
      tags: ["信息不丢失", "等价命题", "概念枢纽"],
      intro: `可逆矩阵把等价条件放在同一张图里理解：网格没有被压扁，列向量张成全空间，秩满，方程 ${texInline("Ax=b")} 对每个 ${texInline("b")} 有唯一解。`,
      concepts: [
        { label: "几何直觉", text: "可逆意味着空间没有被压到低维对象上。" },
        { label: "代数条件", text: "n 阶矩阵可逆等价于秩为 n，也等价于行最简形为 I。" },
        { label: "方程组视角", text: `${texInline("Ax=b")} 对任意 ${texInline("b")} 有唯一解，说明 ${texInline("A")} 能完整追踪输入。` },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章 矩阵",
        page: "",
        items: ["逆矩阵", "可逆的等价条件", "伴随矩阵与逆矩阵公式"],
      },
      visual: {
        type: "slot",
        label: "可逆性对照",
        title: "图示：可逆与坍缩",
        description: "并排比较可逆与不可逆：左侧网格仍铺满平面，右侧网格坍缩成直线。",
        text: `观察 ${texInline("\\det A")} 接近 0 时网格面积怎样变化，再把几何坍缩与 ${texInline("\\operatorname{rank}(A)<n")} 联系起来。`,
        prompts: [
          `让 ${texInline("\\det A")} 从非零逐渐变到 ${texInline("0")}，观察网格面积变化。`,
          "面积为 0 时，多个点落到同一条线上，信息无法完整恢复。",
          `把几何坍缩与 ${texInline("\\operatorname{rank}(A)<n")}、${texInline("Ax=b")} 的解联系起来。`,
        ],
      },
      example: {
        title: "例题 4.5：不用求逆判断可逆",
        question: "设 A 的三列向量线性相关。A 可能可逆吗？为什么？",
        steps: [
          `三列线性相关说明列空间维数小于 ${texInline("3")}。`,
          `于是 ${texInline("\\operatorname{rank}(A)<3")}。`,
          "对 3 阶矩阵来说，满秩才可能可逆。几何上看，A 至少让某个非零方向丢失信息。",
        ],
      },
      summary: ["可逆等价于满秩。", "几何上，可逆变换不会把空间压到低维对象。"],
      exercises: [`用秩判断 ${texInline("\\begin{bmatrix}1&2&3\\\\2&4&6\\\\0&1&1\\end{bmatrix}")} 是否可逆。`],
    },
    {
      id: "matrix-rank",
      number: "4.6",
      textbookSection: "§4.6",
      title: "矩阵的秩：列空间、行空间与标准形",
      navTitle: "秩与等价标准形",
      question: "秩到底在数什么？它为什么既可以从列看，也可以从行看？",
      goal: "把秩理解成矩阵真正保留下来的维度，并连接行等价、列等价与标准形。",
      tags: ["列空间", "行空间", "重点交互"],
      intro:
        "秩描述矩阵作为变换时保留下来的有效维度。消元法给了计算秩的工具，列空间和行空间给了秩的含义。",
      concepts: [
        { label: "列秩", text: "列向量张成空间的维数，描述输出能到达的范围。" },
        { label: "行秩", text: "行向量张成空间的维数，最终与列秩相等。" },
        { label: "标准形", text: `经初等变换可化为 ${texInline("\\operatorname{diag}(I_r,0)")}，${texInline("r")} 就是秩。` },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章 矩阵",
        page: "",
        items: ["矩阵的秩", "等价标准形", "行秩与列秩"],
      },
      visual: {
        type: "rank",
        title: "交互图：秩是保留下来的维度",
        description: "比较列向量张成平面和坍缩成直线时的差别。",
        prompts: [
          "从三列向量出发，观察它们张成平面还是只张成直线。",
          "切换到行变换，展示消元不改变秩。",
          "最后把矩阵压缩到标准形，只保留 r 个独立方向。",
        ],
      },
      example: {
        title: "例题 4.6：从列关系判断秩",
        question: `矩阵 ${texInline("A")} 的三列满足 ${texInline("c_3=2c_1-c_2")}，且 ${texInline("c_1,c_2")} 线性无关。${texInline("\\operatorname{rank}(A)")} 是多少？`,
        steps: [
          "第三列已经由前两列线性表示，所以不提供新方向。",
          `前两列 ${texInline("c_1,c_2")} 线性无关，所以至少有两个独立方向。`,
          `列空间维数正好是 ${texInline("2")}，因此 ${texInline("\\operatorname{rank}(A)=2")}。`,
        ],
      },
      summary: ["秩是有效维度。", "列秩与行秩相等，消元给出计算路径。"],
      exercises: ["构造一个 3 列矩阵，使三列都非零但秩为 1。"],
    },
    {
      id: "block-matrices",
      number: "4.7",
      textbookSection: "§4.7",
      title: "分块矩阵与结构化计算",
      navTitle: "分块矩阵",
      question: "为什么把大矩阵切成小块以后，计算会更清楚？分块在表达什么结构？",
      goal: "把大矩阵拆成有意义的小矩阵，让计算服务于结构。",
      tags: ["结构化", "块乘法", "空间分解"],
      intro:
        "分块矩阵是组织复杂信息的工具。当线性映射尊重某种分解时，矩阵会呈现出更清楚的结构。",
      concepts: [
        { label: "块乘法", text: "只要尺寸匹配，块可以像元素一样参与乘法。" },
        { label: "块对角", text: "不同子空间互不耦合时，矩阵会呈现块对角结构。" },
        { label: "结构优先", text: "分块的目的在于暴露问题内部的独立部分。" },
      ],
      textbook: {
        reference: "北大版《高等代数》第四章 矩阵",
        page: "",
        items: ["分块矩阵", "块乘法", "块对角矩阵"],
      },
      visual: {
        type: "block",
        title: "图示：把大矩阵看成小系统",
        description: "分块让输入、输出和子结构更清楚。",
        prompts: [
          "把一个大矩阵切成四块，并标出每块的输入输出含义。",
          "演示块乘法时，只高亮真正发生配对的块。",
          "用块对角矩阵展示两个子系统互不干扰的情况。",
        ],
      },
      example: {
        title: "例题 4.7：块对角矩阵的逆",
        question: `若 ${texInline("A,D")} 都可逆，为什么 ${texInline("\\operatorname{diag}(A,D)")} 的逆是 ${texInline("\\operatorname{diag}(A^{-1},D^{-1})")}？`,
        steps: [
          "块对角矩阵表示两个部分互不混合。",
          `${texInline("\\operatorname{diag}(A,D)\\operatorname{diag}(A^{-1},D^{-1})=\\operatorname{diag}(AA^{-1},DD^{-1})")}。`,
          `${texInline("AA^{-1}=I")} 且 ${texInline("DD^{-1}=I")}，所以乘积为 ${texInline("\\operatorname{diag}(I,I)")}。`,
        ],
      },
      summary: ["分块矩阵让结构先被看见。", "块对角矩阵可以按子系统分别处理。"],
      exercises: [`验证 ${texInline("\\begin{bmatrix}A&0\\\\0&D\\end{bmatrix}\\begin{bmatrix}B&0\\\\0&E\\end{bmatrix}=\\begin{bmatrix}AB&0\\\\0&DE\\end{bmatrix}")}。`],
    },
  ],
});
