(() => {
  const I = (source) => (window.texInline ? window.texInline(source) : `<code>${source}</code>`);
  const chapterReference = "北大版《高等代数》第八章";

  const sections = [
    {
      id: "lambda-matrix",
      number: "§1",
      textbookSection: "λ-矩阵",
      title: "λ-矩阵",
      navTitle: "λ-矩阵",
      question: "把常数矩阵变成关于 λ 的多项式矩阵以后，我们究竟多看见了什么？",
      goal: "区分普通矩阵、一般 λ-矩阵与特征矩阵，并把特征值理解成特征矩阵出现非零核的参数。",
      tags: ["F[λ]", "特征矩阵", "奇异参数"],
      intro:
        `这一节只抓住一条主线：先从普通矩阵 ${I("A")} 构造 ${I("\\lambda I-A")}，再让参数 ${I("\\lambda")} 移动。你要观察的不是曲线本身，而是行列式归零时，矩阵怎样从“只能把 0 送到 0”突然变成“出现一整条非零解方向”。`,
      observe: {
        title: "先盯住同一件事的四种信号",
        lead: `当 ${I("\\lambda")} 经过特征值时，下面四件事必须同时发生。实验中每次只追踪这四个信号。`,
        cues: [
          `特征多项式在当前位置取值为 0。`,
          `特征矩阵 ${I("\\lambda I-A")} 的秩下降。`,
          `齐次方程出现非零解，核空间变大。`,
          `核中的非零方向就是当前特征值对应的特征方向。`,
        ],
      },
      interactive: {
        kind: "lambda-story",
        title: "从构造特征矩阵到看见非零核",
        description: "先看每个元素如何进入 λI−A，再扫描参数，最后比较两个拥有同一重根却结构不同的矩阵。",
        mission: "解释为什么 2I 与一个二阶 Jordan 块有相同特征多项式，却拥有不同数量的特征方向。",
        steps: [
          { action: "构造", watch: "对角位置出现 λ−aᵢᵢ，非对角位置只改变符号。" },
          { action: "扫描", watch: "参数到达根时，det、rank、ker 三个读数同步变化。" },
          { action: "对比", watch: "同一个 (λ−2)² 可以对应二维核，也可以只对应一维核。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "λ-矩阵是多项式矩阵",
          subtitle: "先不要把 λ 当作一个已经代入的数。",
          body: `λ-矩阵的每个元素都属于多项式环 ${I("F[\\lambda]")}。它可以是任意多项式矩阵；${I("\\lambda I-A")} 只是最重要的一类。`,
          formula: "A(\\lambda)=[a_{ij}(\\lambda)]\\in M_{m\\times n}(F[\\lambda]).",
        },
        {
          number: "02",
          title: "多项式环中的可逆与数值代入不同",
          subtitle: "某次代入可逆，不代表这个 λ-矩阵可逆。",
          body: `方阵 ${I("A(\\lambda)")} 在 ${I("F[\\lambda]")} 上可逆，当且仅当行列式是非零常数。比如一阶矩阵 ${I("[\\lambda]")} 在 ${I("\\lambda=2")} 时是数值 2，但作为 λ-矩阵没有多项式逆。`,
          formula: "A(\\lambda)\\in GL_n(F[\\lambda])\\Longleftrightarrow\\det A(\\lambda)\\in F^\\times.",
        },
        {
          number: "03",
          title: "特征值是出现非零核的参数",
          subtitle: "把特征向量方程移到一边即可看见。",
          body: `${I("Av=\\lambda_0v")} 等价于 ${I("(\\lambda_0I-A)v=0")}，并且要求 ${I("v\\ne0")}。因此特征值、行列式为零、秩下降和非零核出现，是同一事件的四种表达。`,
          formula: "\\lambda_0\\in\\sigma(A)\\Longleftrightarrow\\det(\\lambda_0I-A)=0\\Longleftrightarrow\\ker(\\lambda_0I-A)\\ne\\{0\\}.",
        },
        {
          number: "04",
          title: "重根还不够决定特征方向的数量",
          subtitle: "代数重数与几何重数必须分开。",
          body: `特征多项式中根的重数是代数重数；特征空间 ${I("\\ker(\\lambda_0I-A)")} 的维数是几何重数。二者可能相等，也可能不相等。`,
        },
      ],
      example: {
        title: "重特征值为什么还不能决定对角化",
        question: `设 ${I("A=\\begin{bmatrix}2&1\\\\0&2\\end{bmatrix}")}。写出 ${I("\\lambda I-A")}，求特征多项式，并判断 ${I("\\lambda=2")} 时核的维数。`,
        choices: [
          { text: `${I("\\chi_A=(\\lambda-2)^2")}，核维数为 2。`, correct: false },
          { text: `${I("\\chi_A=(\\lambda-2)^2")}，核维数为 1。`, correct: true },
          { text: `${I("\\chi_A=\\lambda^2-2")}，核维数为 1。`, correct: false },
          { text: `根的重数已经是 2，不必再计算核。`, correct: false },
        ],
        steps: [
          `${I("\\lambda I-A=\\begin{bmatrix}\\lambda-2&-1\\\\0&\\lambda-2\\end{bmatrix}")}。`,
          `${I("\\chi_A(\\lambda)=\\det(\\lambda I-A)=(\\lambda-2)^2")}。`,
          `代入 ${I("\\lambda=2")} 得 ${I("\\begin{bmatrix}0&-1\\\\0&0\\end{bmatrix}")}，秩为 1。`,
          `方程给出 ${I("y=0")}，只有一个自由变量，所以核维数为 1。`,
          `代数重数 2 大于几何重数 1，因此缺少一个独立特征向量。`,
        ],
      },
      quiz: [
        { question: "一般 λ-矩阵的元素属于什么集合？", answer: `${I("F[\\lambda]")}。` },
        { question: `${I("[\\lambda]")} 作为一阶 λ-矩阵可逆吗？`, answer: `不可逆，因为其行列式不是非零常数。` },
        { question: `为什么 ${I("\\lambda_0")} 是特征值时会出现非零核？`, answer: `${I("Av=\\lambda_0v")} 等价于 ${I("(\\lambda_0I-A)v=0")}，并要求 ${I("v\\ne0")}。` },
        { question: "相同特征多项式是否保证矩阵相似？", answer: "不保证，还需要比较更细的结构不变量。" },
      ],
      misconceptions: ["把 λ 当成已经固定的数", "把所有非零多项式都当作单位", "把代数重数直接当成核维数"],
      summary: [
        `${I("\\lambda I-A")} 把特征值问题改写成“何时出现非零核”。`,
        `行列式为零、秩下降和核空间增大是同一结构变化。`,
        `相同的根及重数仍可能对应不同的核结构；下一节将提取更稳定的标准形。`,
      ],
      textbook: { reference: chapterReference, items: ["λ-矩阵的定义", "可逆 λ-矩阵", "特征矩阵与特征值"] },
    },
    {
      id: "smith-form",
      number: "§2",
      textbookSection: "λ-矩阵在初等变换下的标准形",
      title: "λ-矩阵在初等变换下的标准形",
      navTitle: "λ-矩阵标准形",
      question: "怎样把复杂 λ-矩阵化成一眼能读出整除结构的对角形？",
      goal: "理解 λ-矩阵的合法行列初等变换、等价关系和 Smith 标准形。",
      tags: ["等价", "行列变换", "Smith 标准形"],
      intro:
        `这里的目标不是得到阶梯形，而是保留等价类的前提下，把矩阵化成 ${I("\\operatorname{diag}(d_1,\\ldots,d_r,0,\\ldots,0)")}。实验中每一步都要回答两件事：这一步是左乘还是右乘？它为什么可逆？`,
      observe: {
        title: "别只盯最后的对角矩阵",
        lead: "Smith 化简真正要看的是同一个对象怎样在合法操作下连续变简单。",
        cues: [
          "行操作对应左乘，列操作对应右乘。",
          "倍乘只能使用非零常数；乘以 λ 会破坏可逆性。",
          "一个单位 1 出现后，可以把同一行和同一列的其余元素清零。",
          `${I("d_1\\mid d_2\\mid\\cdots")} 是最终结构，不只是排列要求。`,
        ],
      },
      interactive: {
        kind: "smith-story",
        title: "Smith 化简工作台",
        description: `对 ${I("A(\\lambda)=\\begin{bmatrix}\\lambda&1\\\\\\lambda^2-1&\\lambda+1\\end{bmatrix}")} 做四步操作，观察矩阵、操作方向与整除链同步变化。`,
        mission: `说明为什么最后得到的 ${I("\\operatorname{diag}(1,\\lambda+1)")} 与原矩阵等价，而不是相似。`,
        steps: [
          { action: "换列", watch: "把单位 1 移到左上角，建立最方便的主元。" },
          { action: "消行", watch: "用多项式倍加清掉左下角；操作仍然可逆。" },
          { action: "消列", watch: "用左上角的 1 清掉右上角。" },
          { action: "首一化", watch: "只乘非零常数 −1，使最后一个因子首一。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "合法变换有六类",
          subtitle: "行和列各有三类。",
          body: "交换两行或两列；把一行或一列乘以非零常数；把另一行或列的多项式倍数加到本行或本列。每一步都有可逆的反操作。",
        },
        {
          number: "02",
          title: "等价是左右两侧分别作用",
          subtitle: "它与相似不是同一种关系。",
          body: `若 ${I("B(\\lambda)=U(\\lambda)A(\\lambda)V(\\lambda)")}，其中 ${I("U,V")} 在 ${I("F[\\lambda]")} 上可逆，则称 ${I("A,B")} 等价。左右因子一般不同，也不要求互为逆。`,
          formula: "B(\\lambda)=U(\\lambda)A(\\lambda)V(\\lambda).",
        },
        {
          number: "03",
          title: "Smith 标准形具有整除链",
          subtitle: "对角化还不够，顺序也包含结构。",
          body: `非零对角元首一，并满足 ${I("d_1\\mid d_2\\mid\\cdots\\mid d_r")}。在这些规范下，标准形唯一。`,
          formula: "\\operatorname{diag}(d_1,\\ldots,d_r,0,\\ldots,0),\\qquad d_1\\mid d_2\\mid\\cdots\\mid d_r.",
        },
        {
          number: "04",
          title: "欧几里得算法负责制造可整除关系",
          subtitle: "出现余数时继续做带余除法。",
          body: "若两个候选对角元互不整除，就用多项式带余除法把较大者减去较小者的倍数，把余数送回矩阵，直到余数为零。",
        },
      ],
      example: {
        title: "把一个 2×2 λ-矩阵化为 Smith 标准形",
        question: `把 ${I("A(\\lambda)=\\begin{bmatrix}\\lambda&1\\\\\\lambda^2-1&\\lambda+1\\end{bmatrix}")} 化为 Smith 标准形。`,
        steps: [
          `交换两列，得到 ${I("\\begin{bmatrix}1&\\lambda\\\\\\lambda+1&\\lambda^2-1\\end{bmatrix}")}。`,
          `做 ${I("R_2\\leftarrow R_2-(\\lambda+1)R_1")}，得到 ${I("\\begin{bmatrix}1&\\lambda\\\\0&-\\lambda-1\\end{bmatrix}")}。`,
          `做 ${I("C_2\\leftarrow C_2-\\lambda C_1")}，得到 ${I("\\begin{bmatrix}1&0\\\\0&-\\lambda-1\\end{bmatrix}")}。`,
          `做 ${I("R_2\\leftarrow-R_2")}，得到 ${I("\\operatorname{diag}(1,\\lambda+1)")}。`,
          `${I("1\\mid(\\lambda+1)")} 且两个非零对角元都首一，所以这就是 Smith 标准形。`,
        ],
      },
      quiz: [
        { question: "把一行乘以 λ 是否是合法初等变换？", answer: "不是。λ 不是多项式环中的单位。" },
        { question: "行操作与列操作分别对应矩阵哪一侧？", answer: "行操作对应左乘，列操作对应右乘。" },
        { question: "为什么只得到对角形还不一定是 Smith 标准形？", answer: "还要首一并满足逐项整除链。" },
        { question: "等价关系是否要求右因子等于左因子的逆？", answer: "不要求；那是相似关系中的特殊结构。" },
      ],
      misconceptions: ["把倍乘多项式也当作合法操作", "把等价误写成相似", "只看对角不检查整除链"],
      summary: [
        `λ-矩阵通过可逆行列操作变到 Smith 标准形。`,
        `等价写成 ${I("B=UAV")}，与 ${I("P^{-1}AP")} 的相似关系不同。`,
        `下一节将从 Smith 对角元中提取不会随等价变换改变的不变因子。`,
      ],
      textbook: { reference: chapterReference, items: ["λ-矩阵的初等变换", "等价", "Smith 标准形"] },
    },
    {
      id: "invariant-factors",
      number: "§3",
      textbookSection: "不变因子",
      title: "不变因子",
      navTitle: "不变因子",
      question: "为什么 Smith 对角元不会随等价变换改变？怎样从所有子式中直接恢复它们？",
      goal: "理解行列式因子与不变因子的关系，并读出特征多项式和最小多项式。",
      tags: ["行列式因子", "整除链", "最小多项式"],
      intro:
        `这节不要把公式 ${I("d_k=\\Delta_k/\\Delta_{k-1}")} 当成记号题。你要亲眼看见三层对象：先收集所有 ${I("k")} 阶子式，再取最大公因式 ${I("\\Delta_k")}，最后相邻相除得到 ${I("d_k")}。`,
      observe: {
        title: "一条从许多子式压缩到少数因子的流水线",
        lead: "操作中始终看清输入、压缩规则和输出。",
        cues: [
          `${I("\\Delta_k")} 来自全部 k 阶子式的首一最大公因式。`,
          `初等行列变换会混合子式，但不会改变这些 gcd。`,
          `${I("d_k=\\Delta_k/\\Delta_{k-1}")} 自动形成整除链。`,
          `对 ${I("\\lambda I-A")} 而言，最后一个不变因子是最小多项式。`,
        ],
      },
      interactive: {
        kind: "invariant-story",
        title: "子式—gcd—不变因子流水线",
        description: "逐级选择 1 阶、2 阶和 3 阶子式，观察它们怎样被压缩成 Δ₁、Δ₂、Δ₃，再相除得到 d₁、d₂、d₃。",
        mission: "比较 2I 与二阶 Jordan 块：它们有相同特征多项式，为什么不变因子链不同？",
        steps: [
          { action: "收集子式", watch: "同一阶的所有子式一起进入 gcd 机器。" },
          { action: "读取 Δₖ", watch: "每个 Δₖ 是这一阶全部子式的共同多项式因子。" },
          { action: "相邻相除", watch: "dₖ 不是新的猜测，而是 Δₖ/Δₖ₋₁。" },
          { action: "比较指纹", watch: "相同 χ 可以对应不同的不变因子链与最小多项式。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "行列式因子由所有同阶子式决定",
          subtitle: "不是随便挑一个非零子式。",
          body: `${I("\\Delta_k(\\lambda)")} 定义为全部 ${I("k")} 阶子式的首一最大公因式，并约定 ${I("\\Delta_0=1")}。`,
          formula: "\\Delta_k=\\gcd\\{M_k^{(1)},M_k^{(2)},\\ldots,M_k^{(N_k)}\\}.",
        },
        {
          number: "02",
          title: "不变因子来自相邻行列式因子之商",
          subtitle: "这一步把累计信息拆成逐层新增信息。",
          body: `${I("d_k=\\Delta_k/\\Delta_{k-1}")}。由行列式因子的整除关系可得 ${I("d_1\\mid d_2\\mid\\cdots")}。`,
          formula: "d_k=\\frac{\\Delta_k}{\\Delta_{k-1}},\\qquad\\Delta_k=d_1d_2\\cdots d_k.",
        },
        {
          number: "03",
          title: "不变因子完整记录 Smith 标准形",
          subtitle: "它们在等价变换下保持不变。",
          body: "Smith 标准形的非零对角元正是不变因子。因此两个 λ-矩阵等价，当且仅当它们的不变因子完全相同。",
        },
        {
          number: "04",
          title: "特征矩阵把分类信息带回普通矩阵",
          subtitle: "乘积给出特征多项式，末项给出最小多项式。",
          body: `若 ${I("\\lambda I-A")} 的非单位不变因子为 ${I("d_1,\\ldots,d_s")}，则它们的乘积是特征多项式，最后一个 ${I("d_s")} 是最小多项式。`,
        },
      ],
      example: {
        title: "由行列式因子恢复不变因子",
        question: `已知 ${I("\\Delta_1=1")}，${I("\\Delta_2=\\lambda-1")}，${I("\\Delta_3=(\\lambda-1)^3(\\lambda+2)")}。求不变因子。`,
        choices: [
          { text: `${I("d_1=1,\\ d_2=\\lambda-1,\\ d_3=(\\lambda-1)^2(\\lambda+2)")}。`, correct: true },
          { text: `${I("d_1=\\lambda-1,\\ d_2=(\\lambda-1)^2,\\ d_3=\\lambda+2")}。`, correct: false },
          { text: `${I("d_1=1,\\ d_2=1,\\ d_3=\\Delta_3")}。`, correct: false },
          { text: `只知道 ${I("\\Delta_3")} 才能求。`, correct: false },
        ],
        steps: [
          `${I("d_1=\\Delta_1/\\Delta_0=1")}。`,
          `${I("d_2=\\Delta_2/\\Delta_1=\\lambda-1")}。`,
          `${I("d_3=\\Delta_3/\\Delta_2=(\\lambda-1)^2(\\lambda+2)")}。`,
          `检查 ${I("1\\mid(\\lambda-1)\\mid(\\lambda-1)^2(\\lambda+2)")}。`,
        ],
      },
      quiz: [
        { question: `${I("\\Delta_k")} 为什么不能由一个任选的 k 阶子式替代？`, answer: "因为它必须是全部 k 阶子式的共同最大因子。" },
        { question: `怎样由 ${I("\\Delta_k")} 得到 ${I("d_k")}？`, answer: `${I("d_k=\\Delta_k/\\Delta_{k-1}")}。` },
        { question: "特征矩阵最后一个不变因子是什么？", answer: "矩阵的最小多项式。" },
        { question: "特征多项式与不变因子的关系是什么？", answer: "所有非单位不变因子的乘积等于特征多项式。" },
      ],
      misconceptions: ["用某一个最大子式代替全部子式的 gcd", "把 Δₖ 与 dₖ 混在一起", "认为特征多项式已经包含全部相似信息"],
      summary: [
        `${I("\\Delta_k")} 压缩同阶全部子式的信息，${I("d_k")} 则记录每一层新增加的因子。`,
        `不变因子完整决定 Smith 标准形，并且对特征矩阵给出最小多项式与特征多项式。`,
        `下一节将用这条指纹判定两个普通矩阵是否相似。`,
      ],
      textbook: { reference: chapterReference, items: ["行列式因子", "不变因子", "特征多项式与最小多项式"] },
    },
    {
      id: "similarity-criterion",
      number: "§4",
      textbookSection: "矩阵相似的条件",
      title: "矩阵相似的条件",
      navTitle: "矩阵相似的条件",
      question: "数值完全不同的两个矩阵，什么时候只是同一个线性变换在不同基下的坐标？",
      goal: "从换基视角理解相似，并用特征矩阵的不变因子给出完整判据。",
      tags: ["换基", "P⁻¹AP", "相似分类"],
      intro:
        `相似不是“矩阵看起来接近”，而是同一个线性变换换了一组基。实验先让同一个变换在两套坐标中显示为两个不同矩阵，再逐层检查迹、行列式、特征多项式、最小多项式和不变因子。`,
      observe: {
        title: "先分清对象与坐标",
        lead: "相似变化中，线性变换本身没有换，改变的是描述它的坐标语言。",
        cues: [
          `同一个向量和同一个线性变换，在不同基下坐标会改变。`,
          `${I("B=P^{-1}AP")} 中的 ${I("P")} 负责把新坐标翻译到旧坐标。`,
          `迹、行列式和特征多项式是必要条件，但通常不够。`,
          `完整判据是 ${I("\\lambda I-A")} 与 ${I("\\lambda I-B")} 有相同不变因子。`,
        ],
      },
      interactive: {
        kind: "similarity-story",
        title: "同一变换的双坐标房间与结构护照",
        description: "先切换两组基，观察同一变换的矩阵描述改变；再逐页打开结构护照，比较一对真相似矩阵与一对伪相似矩阵。",
        mission: "解释为什么 2I 与二阶 Jordan 块具有相同迹、行列式和特征多项式，却仍然不相似。",
        steps: [
          { action: "换基", watch: "几何对象保持不动，只有坐标网格与矩阵记录变化。" },
          { action: "检查粗指标", watch: "迹、行列式相同只能通过前两道门。" },
          { action: "检查多项式", watch: "相同特征多项式仍不能排除不同 Jordan 结构。" },
          { action: "打开完整指纹", watch: "不变因子一致才给出相似结论。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "相似来自换基",
          subtitle: "矩阵变化，线性变换不变。",
          body: `设两组基之间的过渡矩阵为 ${I("P")}。同一线性变换在两组基下的矩阵分别为 ${I("A,B")}，则 ${I("B=P^{-1}AP")}。`,
          formula: "B=P^{-1}AP.",
        },
        {
          number: "02",
          title: "相似会诱导特征矩阵等价",
          subtitle: "把常数换基矩阵放到 λ-矩阵两侧。",
          body: `${I("B=P^{-1}AP")} 推出 ${I("\\lambda I-B=P^{-1}(\\lambda I-A)P")}。因此两者的 Smith 标准形与不变因子相同。`,
          formula: "\\lambda I-B=P^{-1}(\\lambda I-A)P.",
        },
        {
          number: "03",
          title: "相同特征多项式只是必要条件",
          subtitle: "它只记录不变因子的乘积。",
          body: `矩阵 ${I("2I")} 与二阶 Jordan 块都有特征多项式 ${I("(\\lambda-2)^2")}；前者最小多项式为 ${I("\\lambda-2")}，后者为 ${I("(\\lambda-2)^2")}。`,
        },
        {
          number: "04",
          title: "不变因子给出完整相似判据",
          subtitle: "这是本节的最终分类结论。",
          body: "同阶矩阵 A 与 B 相似，当且仅当它们的特征矩阵 λI−A 与 λI−B 等价，也即不变因子完全相同。",
        },
      ],
      example: {
        title: "用最小多项式排除伪相似",
        question: `判断 ${I("A=2I_2")} 与 ${I("B=\\begin{bmatrix}2&1\\\\0&2\\end{bmatrix}")} 是否相似。`,
        steps: [
          `两者的迹、行列式和特征多项式都相同。`,
          `${I("m_A(\\lambda)=\\lambda-2")}，因为 ${I("A-2I=0")}。`,
          `${I("m_B(\\lambda)=(\\lambda-2)^2")}，因为 ${I("B-2I\\ne0")} 但 ${I("(B-2I)^2=0")}。`,
          `最小多项式不同，所以不变因子不同，故不相似。`,
        ],
      },
      quiz: [
        { question: "相似关系改变了线性变换本身吗？", answer: "没有，只改变了基与坐标表示。" },
        { question: "相同迹和行列式是否保证相似？", answer: "不保证。" },
        { question: "相同特征多项式是否保证相似？", answer: "不保证。" },
        { question: "什么条件完整刻画相似？", answer: "特征矩阵具有相同不变因子。" },
      ],
      misconceptions: ["把主动变换与被动换基混为一谈", "只比较特征值集合", "把必要条件当成充分条件"],
      summary: [
        `相似矩阵是同一线性变换在不同基下的坐标记录。`,
        `${I("B=P^{-1}AP")} 使特征矩阵保持相同的不变因子。`,
        `相同特征多项式仍可能不相似；完整判据是不变因子完全一致。`,
      ],
      textbook: { reference: chapterReference, items: ["相似与换基", "特征矩阵等价", "相似的充要条件"] },
    },
    {
      id: "elementary-divisors",
      number: "§5",
      textbookSection: "初等因子",
      title: "初等因子",
      navTitle: "初等因子",
      question: "把不变因子继续分解成不可约多项式的幂以后，怎样看见每个局部标准块？",
      goal: "理解初等因子的定义、底域依赖，以及不变因子与初等因子之间的拆分和重组。",
      tags: ["不可约因子", "幂", "底域"],
      intro:
        `不变因子按“整除层”排列；初等因子按“不可约多项式族”拆开。实验会把每个不变因子做成一排彩色积木，再按照不可约因子重新归类。颜色代表不可约因子，积木高度代表幂次。`,
      observe: {
        title: "始终保持两条视觉规则",
        lead: "同一种不可约因子始终使用同一颜色；幂次始终用层数或高度表示。",
        cues: [
          `先在指定底域中判断哪些因子不可约。`,
          `每个不可约因子的幂单独成为一个初等因子。`,
          `换到底域更大时，原来不可约的因子可能继续分裂。`,
          `把同族幂次按列重新对齐，可以恢复不变因子链。`,
        ],
      },
      interactive: {
        kind: "elementary-story",
        title: "初等因子积木墙",
        description: "在 R 与 C 之间切换，观察 λ²+1 是否分裂；再把不变因子拆成幂块并按列重组。",
        mission: `说明为什么 ${I("\\lambda^2+1")} 在 ${I("\\mathbb R")} 上对应一个不可约族，而在 ${I("\\mathbb C")} 上变成 ${I("\\lambda-i")} 与 ${I("\\lambda+i")} 两个族。`,
        steps: [
          { action: "选底域", watch: "不可约因子的定义依赖底域。" },
          { action: "拆分", watch: "每个 p(λ)^e 单独成为一个初等因子块。" },
          { action: "按族归类", watch: "同色块放到同一列，幂次用高度表示。" },
          { action: "重组", watch: "从各列按层相乘，重新得到整除排列的不变因子。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "初等因子是不可约多项式的幂",
          subtitle: "先分解，再把每个幂单独列出。",
          body: `若不变因子分解为 ${I("d_i=\\prod_j p_j(\\lambda)^{e_{ij}}")}，则所有非零的 ${I("p_j^{e_{ij}}")} 就是初等因子。`,
        },
        {
          number: "02",
          title: "底域决定什么叫不可约",
          subtitle: "同一个多项式在不同域上可能拥有不同拆法。",
          body: `${I("\\lambda^2+1")} 在 ${I("\\mathbb R")} 上不可约，而在 ${I("\\mathbb C")} 上分解为 ${I("(\\lambda-i)(\\lambda+i)")}。因此初等因子必须连同底域一起讨论。`,
        },
        {
          number: "03",
          title: "不变因子与初等因子包含同样的信息",
          subtitle: "它们只是按不同方向组织。",
          body: "不变因子按整除链横向排列；初等因子按不可约因子族纵向排列。给定其中一套，可以唯一恢复另一套。",
        },
        {
          number: "04",
          title: "线性因子的幂预告 Jordan 块大小",
          subtitle: "完全分裂时，指数就是链长度。",
          body: `在分裂域中，初等因子 ${I("(\\lambda-\\lambda_0)^e")} 将对应一个大小为 ${I("e")} 的 Jordan 块。`,
        },
      ],
      example: {
        title: "从不变因子列出初等因子",
        question: `在 ${I("\\mathbb R")} 上，设 ${I("d_1=(\\lambda-1)(\\lambda^2+1)")}，${I("d_2=(\\lambda-1)^2(\\lambda^2+1)^2")}。列出全部初等因子。`,
        steps: [
          `${I("\\lambda-1")} 与 ${I("\\lambda^2+1")} 在 ${I("\\mathbb R")} 上都是首一不可约多项式。`,
          `由 ${I("d_1")} 得到初等因子 ${I("\\lambda-1")} 与 ${I("\\lambda^2+1")}。`,
          `由 ${I("d_2")} 得到初等因子 ${I("(\\lambda-1)^2")} 与 ${I("(\\lambda^2+1)^2")}。`,
          `共四个初等因子；重复因子与指数都必须保留。`,
        ],
      },
      quiz: [
        { question: "初等因子是否可以是两个不同不可约多项式的乘积？", answer: "不可以；它必须是单个首一不可约多项式的正整数幂。" },
        { question: "改变底域会不会改变初等因子？", answer: "可能会，因为不可约分解会改变。" },
        { question: `${I("(\\lambda-2)^3")} 中的指数 3 表示什么结构预告？`, answer: "在分裂域中预告一个长度为 3 的 Jordan 链或 3 阶 Jordan 块。" },
        { question: "不变因子与初等因子能否互相恢复？", answer: "可以，二者包含同样的分类信息。" },
      ],
      misconceptions: ["忽略底域", "合并重复初等因子", "把不同不可约因子的乘积当作一个初等因子"],
      summary: [
        `初等因子把不变因子拆成不可约多项式的幂。`,
        `底域改变时，不可约分解以及初等因子都可能改变。`,
        `在线性分裂情形，幂次将直接变成 Jordan 链长度。`,
      ],
      textbook: { reference: chapterReference, items: ["初等因子的定义", "不变因子与初等因子的互换", "底域与不可约分解"] },
    },
    {
      id: "jordan-derivation",
      number: "§6",
      textbookSection: "若尔当标准形的理论推导",
      title: "若尔当标准形的理论推导",
      navTitle: "若尔当标准形推导",
      question: "当特征向量不够时，怎样用广义特征向量补齐一组基，并从核增长反推出 Jordan 块？",
      goal: "用广义特征向量链和核空间增长解释 Jordan 块的来源、数量与大小。",
      tags: ["广义特征向量", "Jordan 链", "核增长"],
      intro:
        `本节不把 Jordan 标准形当成现成答案。先固定一个特征值 ${I("\\lambda_0")}，令 ${I("N=A-\\lambda_0I")}。实验会把向量排成向下流动的链：每施加一次 ${I("N")} 就向下一层，最终落到 0。链有多长，Jordan 块就有多大。`,
      observe: {
        title: "先看链，再看矩阵",
        lead: "Jordan 块的超对角线 1，来自链中“上一个向量被 N 送到下一个向量”的关系。",
        cues: [
          `${I("Nv_1=0")}：链底端是普通特征向量。`,
          `${I("Nv_2=v_1,\\ Nv_3=v_2")}：更高层是广义特征向量。`,
          `${I("\\dim\\ker N^k")} 的增长量等于长度至少为 k 的链数。`,
          `核增长停止时，最长链长度也就确定了。`,
        ],
      },
      interactive: {
        kind: "jordan-story",
        title: "Jordan 链塔与核增长阶梯",
        description: "亲手把两个链塔搭成长度 3 和长度 2，再用 ker N、ker N²、ker N³ 的维数增长反推出块大小。",
        mission: `仅根据 ${I("0,2,4,5")} 这组核维数，说明为什么 Jordan 块大小必须是 3 和 2。`,
        steps: [
          { action: "搭链底", watch: "ker N 的维数等于 Jordan 块的总数。" },
          { action: "向上延长", watch: "每增加一层，就表示这一条链还能再向上延伸。" },
          { action: "读取核增长", watch: "νₖ−νₖ₋₁ 是长度至少为 k 的链数。" },
          { action: "写出 Jordan 块", watch: "每座链塔对应一个 Jordan 块，塔高就是块大小。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "广义特征向量属于某个高次核",
          subtitle: "普通特征向量只是第一层。",
          body: `若 ${I("(A-\\lambda_0I)^kv=0")}，则 ${I("v")} 是对应于 ${I("\\lambda_0")} 的广义特征向量。`,
          formula: "v\\in\\ker(A-\\lambda_0I)^k.",
        },
        {
          number: "02",
          title: "Jordan 链把 N 的作用写成向下移动",
          subtitle: "每个向量都被送到它下面的一个。",
          body: `链 ${I("v_1,\\ldots,v_s")} 满足 ${I("Nv_1=0")} 与 ${I("Nv_j=v_{j-1}\\ (j\\ge 2)")}。在这组基下，${I("A=\\lambda_0I+N")} 正好给出一个 Jordan 块。`,
        },
        {
          number: "03",
          title: "核增长记录链塔横截面",
          subtitle: "第 k 次看见的是每座塔前 k 层。",
          body: `令 ${I("\\nu_k=\\dim\\ker N^k")}。则 ${I("b_k=\\nu_k-\\nu_{k-1}")} 是大小至少为 ${I("k")} 的 Jordan 块个数。`,
          formula: "b_k=\\nu_k-\\nu_{k-1}.",
        },
        {
          number: "04",
          title: "精确块数由相邻增长量再作差",
          subtitle: "至少 k 与至少 k+1 的差，就是恰好 k。",
          body: `大小恰好为 ${I("k")} 的块数是 ${I("b_k-b_{k+1}")}。因此核增长序列可以唯一恢复 Jordan 块大小。`,
        },
        {
          number: "05",
          title: "存在条件必须说明底域",
          subtitle: "特征多项式要在底域上完全分裂。",
          body: "若特征多项式在底域上完全分裂，就可以把各个特征值的广义特征空间分别拆成 Jordan 链，从而得到 Jordan 标准形。",
        },
      ],
      example: {
        title: "由核增长恢复 Jordan 块",
        question: `对某个特征值，已知 ${I("\\nu_0=0,\\nu_1=2,\\nu_2=4,\\nu_3=5")}，且以后不再增长。求 Jordan 块大小。`,
        choices: [
          { text: "一个 5 阶块。", correct: false },
          { text: "两个块，大小为 3 和 2。", correct: true },
          { text: "三个块，大小为 2、2、1。", correct: false },
          { text: "两个块，大小都为 2。", correct: false },
        ],
        steps: [
          `${I("b_1=\\nu_1-\\nu_0=2")}，共有两个 Jordan 块。`,
          `${I("b_2=\\nu_2-\\nu_1=2")}，两个块的大小都至少为 2。`,
          `${I("b_3=\\nu_3-\\nu_2=1")}，只有一个块的大小至少为 3。`,
          `以后不增长，说明没有大小至少为 4 的块。`,
          `因此两个块大小分别为 3 和 2。`,
        ],
      },
      quiz: [
        { question: "Jordan 链底端为什么是普通特征向量？", answer: `因为它满足 ${I("(A-\\lambda_0I)v_1=0")}。` },
        { question: `${I("\\dim\\ker N")} 等于什么？`, answer: "对应特征值的 Jordan 块总数，也等于几何重数。" },
        { question: `${I("\\nu_k-\\nu_{k-1}")} 表示什么？`, answer: "大小至少为 k 的 Jordan 块个数。" },
        { question: "Jordan 标准形在任意底域上都存在吗？", answer: "不一定，需要特征多项式在该底域上完全分裂。" },
      ],
      misconceptions: ["把广义特征向量都叫普通特征向量", "只看代数重数不看核增长", "忽略 Jordan 形的分裂条件"],
      summary: [
        `Jordan 块来自广义特征向量链；链长就是块大小。`,
        `${I("\\dim\\ker(A-\\lambda_0I)^k")} 的增长可以唯一恢复块的数量与大小。`,
        `下一节将不用特征根分裂，而用循环子空间和伴随矩阵建立任意域上的标准形。`,
      ],
      textbook: { reference: chapterReference, items: ["广义特征向量", "Jordan 链", "核增长与 Jordan 块", "Jordan 标准形"] },
    },
    {
      id: "rational-canonical-form",
      number: "§7",
      textbookSection: "矩阵的有理标准形",
      title: "矩阵的有理标准形",
      navTitle: "有理标准形",
      question: "当特征多项式在底域上不能完全分裂时，怎样仍然得到唯一的标准形？",
      goal: "从 Krylov 轨道、循环子空间和伴随矩阵理解有理标准形，并与 Jordan 标准形比较。",
      tags: ["Krylov 轨道", "循环子空间", "伴随矩阵"],
      intro:
        `从一个向量 ${I("v")} 出发，连续作用 ${I("A")} 得到 ${I("v,Av,A^2v,\\ldots")}。只要空间有限维，这条轨道最终必然第一次出现线性关系。那条“首次回流公式”会直接写出一个伴随矩阵；多个循环子空间拼在一起，就是有理标准形。`,
      observe: {
        title: "把伴随矩阵看成带反馈的传送带",
        lead: "前几列只负责把基向量向前移动，最后一列负责把超出轨道的向量反馈回来。",
        cues: [
          `${I("v\\mapsto Av\\mapsto A^2v")} 对应伴随矩阵中的移位列。`,
          `第一次线性相关给出最小的回流多项式。`,
          `一个循环子空间对应一个伴随矩阵块。`,
          `不变因子逐项整除，使这些块按唯一顺序拼接。`,
        ],
      },
      interactive: {
        kind: "rational-story",
        title: "Krylov 传送带与伴随矩阵",
        description: `逐次生成 ${I("v,Av,A^2v,A^3v")}；当 ${I("A^3v=-v+2Av")} 出现时，把移位和反馈系数写入伴随矩阵。`,
        mission: `解释为什么多项式 ${I("f(t)=t^3-2t+1")} 的伴随块在任意底域上都能写出，而不需要先求根。`,
        steps: [
          { action: "生成轨道", watch: "只要新向量独立，循环子空间就继续扩张。" },
          { action: "发现回流", watch: "第一次线性相关给出次数最低的消去多项式。" },
          { action: "写入反馈", watch: "最后一列正是回流关系的系数。" },
          { action: "拼接块", watch: "每个不变因子生成一个伴随矩阵块。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "一个向量生成一个循环子空间",
          subtitle: "沿着 A 的作用追踪这个向量的未来。",
          body: `${I("K(A,v)=\\operatorname{span}\\{v,Av,A^2v,\\ldots\\}")}。当某一步第一次线性相关时，之前的向量形成循环子空间的一组基。`,
        },
        {
          number: "02",
          title: "首次线性关系给出回流多项式",
          subtitle: "次数最低是关键。",
          body: `若首次有 ${I("A^rv=-a_0v-a_1Av-\\cdots-a_{r-1}A^{r-1}v")}，则 ${I("f(t)=t^r+a_{r-1}t^{r-1}+\\cdots+a_0")} 消去 ${I("v")}。`,
          formula: "f(A)v=0.",
        },
        {
          number: "03",
          title: "伴随矩阵记录移位与反馈",
          subtitle: "前 r−1 列移位，最后一列回流。",
          body: `在基 ${I("v,Av,\\ldots,A^{r-1}v")} 下，${I("A")} 的矩阵就是 ${I("f")} 的伴随矩阵。它的特征多项式和最小多项式都等于 ${I("f")}。`,
        },
        {
          number: "04",
          title: "不变因子决定伴随块",
          subtitle: "每个非单位不变因子生成一个块。",
          body: `若不变因子为 ${I("d_1\\mid d_2\\mid\\cdots\\mid d_s")}，则有理标准形是 ${I("C(d_1)\\oplus\\cdots\\oplus C(d_s)")}。`,
          formula: "C(d_1)\\oplus\\cdots\\oplus C(d_s).",
        },
        {
          number: "05",
          title: "有理标准形不要求多项式分裂",
          subtitle: "这是它与 Jordan 标准形最重要的区别。",
          body: "伴随矩阵直接由多项式系数构造，因此在任意域上都能建立；Jordan 标准形则通常需要特征多项式在底域上完全分裂。",
        },
      ],
      example: {
        title: "由回流关系写出伴随矩阵",
        question: `在基 ${I("v,Av,A^2v")} 下，若 ${I("A^3v=-v+2Av")}，写出 ${I("A")} 的矩阵。`,
        steps: [
          `${I("A(v)=Av")} 给出第一列 ${I("(0,1,0)^T")}。`,
          `${I("A(Av)=A^2v")} 给出第二列 ${I("(0,0,1)^T")}。`,
          `${I("A(A^2v)=A^3v=-v+2Av")} 给出第三列 ${I("(-1,2,0)^T")}。`,
          `所以矩阵为 ${I("\\begin{bmatrix}0&0&-1\\\\1&0&2\\\\0&1&0\\end{bmatrix}")}。`,
          `对应多项式为 ${I("t^3-2t+1")}。`,
        ],
      },
      quiz: [
        { question: "什么是循环子空间？", answer: `由 ${I("v,Av,A^2v,\\ldots")} 张成并在 ${I("A")} 下保持不变的子空间。` },
        { question: "为什么要取第一次线性相关？", answer: "它给出次数最低的回流多项式。" },
        { question: "伴随矩阵最后一列来自哪里？", answer: "来自最高次轨道向量的回流关系系数。" },
        { question: "有理标准形为什么不要求求出特征值？", answer: "它直接由不变因子多项式的系数构造伴随块。" },
      ],
      misconceptions: ["把任意消去关系都当成首次回流", "把伴随矩阵写成转置约定却不说明", "认为有理标准形也必须在分裂域上"],
      summary: [
        `Krylov 轨道第一次停止扩张时，产生循环子空间的回流多项式。`,
        `伴随矩阵把“向前移位 + 最后一列反馈”写成坐标。`,
        `有理标准形由不变因子的伴随块组成，在任意域上都能建立。`,
      ],
      textbook: { reference: chapterReference, items: ["循环子空间", "伴随矩阵", "有理标准形"] },
    },
  ];

  registerAlgebraChapter({
    id: "ch8",
    icon: "8",
    title: "第八章 λ-矩阵",
    subtitle: "等价 · 不变量 · 标准形",
    summary:
      "本章沿一条结构分类路线展开：先由普通矩阵构造特征矩阵，再用 Smith 标准形提取不变因子；随后用不变因子判定相似，并把同一套分类信息分别组织成初等因子、Jordan 标准形与有理标准形。",
    sections,
  });
})();
