(() => {
  const I = (source) => (window.texInline ? window.texInline(source) : `<code>${source}</code>`);

  const sources = {
    polynomial: "Hoffman–Kunze《Linear Algebra》第 7 章",
    similarity: "Hoffman–Kunze《Linear Algebra》第 7 章；Strang《Introduction to Linear Algebra》第 8.3 节",
    jordan: "Axler《Linear Algebra Done Right》第 8 章；Friedberg–Insel–Spence《Linear Algebra》第 7 章",
    rational: "Hoffman–Kunze《Linear Algebra》第 7 章；Friedberg–Insel–Spence《Linear Algebra》第 7.4 节",
  };

  const sections = [
    {
      id: "lambda-matrix",
      number: "§1",
      textbookSection: "λ-矩阵",
      title: "λ-矩阵",
      navTitle: "λ-矩阵",
      question: "特征多项式会丢失哪些结构？把 A 提升为 λI−A 后，为什么能够继续分类？",
      goal: "把 λ-矩阵理解为多项式环上的矩阵，分清符号矩阵与数值代入，并看见特征矩阵保存的结构多于一个行列式。",
      tags: ["F[λ]", "特征矩阵", "分类起点"],
      intro:
        `迹、行列式和特征多项式都把一个矩阵压缩成少量数据，许多不相似矩阵会得到同样的结果。本节保留完整的 ${I("\\lambda I-A")}，把 ${I("\\lambda")} 当作多项式变量，观察这件新对象怎样同时记录特征值事件和更细的相似结构。`,
      observe: {
        title: "先分清符号对象，再观察数值事件",
        lead: `实验会在 ${I("F[\\lambda]")} 中构造特征矩阵，也会把具体数值代入。两种视角承担不同任务。`,
        cues: [
          `构造 ${I("\\lambda I-A")} 时，对角元变成 ${I("\\lambda-a_{ii}")}，非对角元变成 ${I("-a_{ij}")}。`,
          `保留 ${I("\\lambda")} 时，我们研究的是一个多项式矩阵及其等价类。`,
          `代入 ${I("\\lambda_0")} 后，行列式、秩和核共同判断 ${I("\\lambda_0")} 是否为特征值。`,
          `比较 ${I("2I")} 与二阶 Jordan 块，找出特征多项式没有保留下来的信息。`,
        ],
      },
      interactive: {
        kind: "lambda-story",
        title: "从特征矩阵到分类问题",
        description: "先逐项构造 λI−A，再扫描参数产生的奇异时刻，最后比较两个具有同一重根的矩阵。",
        mission: `说明为什么 ${I("\\det(\\lambda I-A)")} 只能给出特征矩阵的一部分信息，并指出 ${I("2I")} 与二阶 Jordan 块最先出现差异的位置。`,
        steps: [
          { action: "构造", watch: "每个元素怎样进入 λI−A；此时 λ 仍是符号。" },
          { action: "代入", watch: "到达特征值时，det、rank 与 ker 同时改变。" },
          { action: "对比", watch: "同一个 (λ−2)² 可以对应不同的核维数。" },
          { action: "提出分类问题", watch: "下一步需要保留整个多项式矩阵，而非只取行列式。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "λ-矩阵生活在多项式环上",
          subtitle: "矩阵元素可以是任意多项式。",
          body: `域 ${I("F")} 上的一个 ${I("m\\times n")} 型 λ-矩阵，其元素属于 ${I("F[\\lambda]")}。加法和乘法都在这个环中进行；${I("\\lambda I-A")} 是其中与相似分类联系最紧的一类。`,
          formula: "M(\\lambda)=[m_{ij}(\\lambda)]\\in M_{m\\times n}(F[\\lambda]).",
        },
        {
          number: "02",
          title: "可逆性由多项式环的单位决定",
          subtitle: "F[λ] 中只有非零常数拥有多项式逆。",
          body: `方阵 ${I("M(\\lambda)")} 在 ${I("F[\\lambda]")} 上可逆，当且仅当 ${I("\\det M(\\lambda)")} 是非零常数。因此 ${I("[\\lambda]")} 在代入 ${I("\\lambda=2")} 后得到可逆数值矩阵，作为 λ-矩阵仍然不可逆。`,
          formula: "M(\\lambda)\\in GL_n(F[\\lambda])\\Longleftrightarrow\\det M(\\lambda)\\in F^\\times.",
        },
        {
          number: "03",
          title: "特征矩阵把全部参数保留在同一个对象中",
          subtitle: "数值代入只截取其中一个切片。",
          body: `定义 ${I("M_A(\\lambda)=\\lambda I-A")}。代入 ${I("\\lambda_0")} 后，方程 ${I("M_A(\\lambda_0)v=0")} 就是特征向量方程；保留变量时，矩阵中各行各列的多项式关系仍然存在。`,
          formula: "Av=\\lambda_0v\\Longleftrightarrow(\\lambda_0I-A)v=0.",
        },
        {
          number: "04",
          title: "特征多项式只是一次压缩",
          subtitle: "取行列式会把整个矩阵压成一个多项式。",
          body: `${I("\\chi_A(\\lambda)=\\det(\\lambda I-A)")} 记录特征值及代数重数，却不记录每个根处有多少独立特征方向。具有相同特征多项式的矩阵仍可能不相似。`,
        },
        {
          number: "05",
          title: "本章研究特征矩阵的等价类",
          subtitle: "后续标准形将把丢失的信息重新提取出来。",
          body: `第 2、3 节会允许可逆的多项式行、列变换，把 ${I("\\lambda I-A")} 化成唯一的 Smith 标准形。它的对角元将给出判断相似所需的完整不变因子。`,
        },
      ],
      example: {
        title: "同一个重根为什么还不够",
        question: `设 ${I("A=2I_2")}，${I("B=\\begin{bmatrix}2&1\\\\0&2\\end{bmatrix}")}。下面哪一项最直接揭示 ${I("\\chi_A=\\chi_B=(\\lambda-2)^2")} 仍不足以判断相似？`,
        choices: [
          { text: `两者的迹都等于 ${I("4")}。`, correct: false },
          { text: `两者的行列式都等于 ${I("4")}。`, correct: false },
          { text: `${I("\\dim\\ker(2I-A)=2")} 而 ${I("\\dim\\ker(2I-B)=1")}。`, correct: true },
          { text: `两者都只有特征值 ${I("2")}。`, correct: false },
        ],
        steps: [
          `${I("\\lambda I-A=(\\lambda-2)I_2")}，${I("\\lambda I-B=\\begin{bmatrix}\\lambda-2&-1\\\\0&\\lambda-2\\end{bmatrix}")}。`,
          `两个行列式都等于 ${I("(\\lambda-2)^2")}。`,
          `代入 ${I("\\lambda=2")} 后，前一个矩阵为零矩阵，核维数为 2。`,
          `后一个矩阵秩为 1，核维数为 1；它只提供一个独立特征向量。`,
          `特征多项式相同只说明压缩后的结果相同，完整的 λ-矩阵结构仍有差异。`,
        ],
      },
      quiz: [
        { question: "一般 λ-矩阵的元素属于什么集合？", answer: `${I("F[\\lambda]")}。` },
        { question: `${I("[\\lambda]")} 作为一阶 λ-矩阵可逆吗？`, answer: `不可逆，因为 ${I("\\lambda")} 不是 ${I("F[\\lambda]")} 中的单位。` },
        { question: "代入 λ₀ 与保留 λ 分别研究什么？", answer: "代入后研究一个数值矩阵的秩和核；保留变量时研究多项式矩阵的整体结构。" },
        { question: "特征多项式为什么不能完整判定相似？", answer: "它只保留特征矩阵的行列式，不保留全部行列关系与核结构。" },
      ],
      misconceptions: ["把 λ 在一开始就固定成数", "把任意非零多项式当成单位", "把相同特征多项式当成相似的充分条件"],
      summary: [
        `λ-矩阵是在 ${I("F[\\lambda]")} 上研究的多项式矩阵，数值代入只是它的一个切片。`,
        `${I("\\lambda I-A")} 同时容纳所有特征值事件，并保存比行列式更丰富的结构。`,
        `相似分类需要继续研究特征矩阵在可逆行列变换下的完整等价类。`,
      ],
      textbook: { reference: sources.polynomial, items: ["多项式矩阵与单位", "特征矩阵", "特征多项式的信息边界"] },
    },
    {
      id: "smith-form",
      number: "§2",
      textbookSection: "λ-矩阵在初等变换下的标准形",
      title: "λ-矩阵在初等变换下的标准形",
      navTitle: "λ-矩阵标准形",
      question: "当矩阵中没有现成的单位主元时，欧几里得算法怎样仍把它推进到 Smith 标准形？",
      goal: "理解多项式矩阵的合法行列变换，并沿着 gcd、次数下降和整除链看见 Smith 标准形存在的原因。",
      tags: ["等价", "欧几里得算法", "Smith 标准形"],
      intro:
        `数域上的消元依靠除法，多项式环上的消元依靠带余除法。核心实验先用一个含单位主元的矩阵核对每步是否合法；随后把同样的动作推广到一般情形，看见余数次数不断下降，最终产生能够整除其余元素的主元。`,
      observe: {
        title: "每一步同时检查方向、可逆性和复杂度",
        lead: "Smith 化简的关键证据来自过程：操作保持等价，非零余数的次数持续下降，最后形成整除链。",
        cues: [
          "行操作对应左乘，列操作对应右乘。",
          `交换、加上另一行或列的多项式倍数、乘以 ${I("F^\\times")} 中的常数，都会保持可逆。`,
          "没有单位主元时，用多项式带余除法制造次数更低的非零余数。",
          `${I("d_1\\mid d_2\\mid\\cdots\\mid d_r")} 是算法终点必须满足的结构条件。`,
        ],
      },
      interactive: {
        kind: "smith-story",
        title: "Smith 化简的合法动作",
        description: `先对 ${I("\\begin{bmatrix}\\lambda&1\\\\\\lambda^2-1&\\lambda+1\\end{bmatrix}")} 完成一次可逆行列化简，再用理论模块解释一般矩阵为何也能完成。`,
        mission: `说明实验中的结果为什么与原矩阵等价，并解释没有现成 ${I("1")} 时带余除法怎样承担“制造主元”的任务。`,
        steps: [
          { action: "移动单位", watch: "交换列只改变位置，并保持等价。" },
          { action: "清除同行同列", watch: "多项式倍加的反操作仍是多项式倍加。" },
          { action: "规范首一", watch: "倍乘只使用非零常数。" },
          { action: "推广", watch: "一般情形以次数下降取代数域中的任意除法。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "合法操作等价于乘可逆多项式矩阵",
          subtitle: "行、列各有交换、倍加和常数倍乘三类。",
          body: `每次行操作可写成左乘一个初等矩阵，每次列操作可写成右乘一个初等矩阵。这些矩阵的行列式都是 ${I("F^\\times")} 中的非零常数，因此在 ${I("F[\\lambda]")} 上可逆。`,
        },
        {
          number: "02",
          title: "等价允许左右两侧独立改变",
          subtitle: "它比相似关系拥有更多操作自由。",
          body: `若存在可逆多项式矩阵 ${I("U(\\lambda),V(\\lambda)")} 使 ${I("N(\\lambda)=U(\\lambda)M(\\lambda)V(\\lambda)")}，就称 ${I("M,N")} 等价。`,
          formula: "N(\\lambda)=U(\\lambda)M(\\lambda)V(\\lambda).",
        },
        {
          number: "03",
          title: "欧几里得算法让主元次数下降",
          subtitle: "余数是算法取得进展的可见证据。",
          body: `若候选主元 ${I("a")} 不能整除某个元素 ${I("b")}，写成 ${I("b=qa+r")} 且 ${I("\\deg r<\\deg a")}。一次倍加操作把余数 ${I("r")} 送入矩阵。重复后，非零主元的次数只能下降有限次，最终得到这一层元素的 gcd。`,
          formula: "b(\\lambda)=q(\\lambda)a(\\lambda)+r(\\lambda),\\qquad\\deg r<\\deg a.",
        },
        {
          number: "04",
          title: "主元整除全部元素后才能清行清列",
          subtitle: "先取得 gcd，再递归处理右下角。",
          body: `把首一 gcd 移到左上角后，它整除矩阵所有元素，便可用倍加操作清空第一行、第一列的其余位置。对剩余子矩阵重复同一过程，得到对角形。`,
        },
        {
          number: "05",
          title: "对角形还要修正为整除链",
          subtitle: "相邻项互不整除时再次调用 gcd。",
          body: `若对角元 ${I("a,b")} 不满足 ${I("a\\mid b")}，行列组合会把 ${I("\\gcd(a,b)")} 放到前一位置，并把保持乘积所需的因子放到后一位置。反复修正后得到逐项整除。`,
        },
        {
          number: "06",
          title: "Smith 存在定理",
          subtitle: "F[λ] 的欧几里得结构保证算法终止。",
          body: `每个多项式矩阵都等价于 ${I("\\operatorname{diag}(d_1,\\ldots,d_r,0,\\ldots,0)")}；非零对角元可取首一，并满足 ${I("d_1\\mid\\cdots\\mid d_r")}。唯一性将在下一节由全部子式的 gcd 给出。`,
          formula: "\\operatorname{diag}(d_1,\\ldots,d_r,0,\\ldots,0),\\qquad d_1\\mid\\cdots\\mid d_r.",
        },
      ],
      example: {
        title: "没有单位主元时怎样制造 1",
        question: `矩阵 ${I("M(\\lambda)=\\operatorname{diag}(\\lambda,\\lambda+1)")} 的 Smith 标准形是什么？`,
        choices: [
          { text: `${I("\\operatorname{diag}(\\lambda,\\lambda+1)")}。`, correct: false },
          { text: `${I("\\operatorname{diag}(1,\\lambda(\\lambda+1))")}。`, correct: true },
          { text: `${I("\\operatorname{diag}(\\lambda(\\lambda+1),1)")}。`, correct: false },
          { text: `${I("\\operatorname{diag}(1,\\lambda+1)")}。`, correct: false },
        ],
        steps: [
          `${I("\\gcd(\\lambda,\\lambda+1)=1")}，因为 ${I("(\\lambda+1)-\\lambda=1")}。`,
          `先做 ${I("C_1\\leftarrow C_1+C_2")}，再做 ${I("R_2\\leftarrow R_2-R_1")}，矩阵中出现单位 ${I("1")}。`,
          `把 ${I("1")} 交换到左上角，再用它清空第一行与第一列。`,
          `可得到 ${I("\\operatorname{diag}(1,-\\lambda(\\lambda+1))")}。`,
          `最后乘非零常数 ${I("-1")} 使末项首一，得到 ${I("\\operatorname{diag}(1,\\lambda(\\lambda+1))")}。`,
        ],
      },
      quiz: [
        { question: "把一行乘以 λ 是否为合法初等变换？", answer: `不是，因为 ${I("\\lambda")} 不是 ${I("F[\\lambda]")} 的单位。` },
        { question: "为什么多项式带余除法一定能推动算法？", answer: "非零余数的次数严格低于原主元，而次数是不能无限下降的非负整数。" },
        { question: "得到对角矩阵后为什么还可能没有结束？", answer: "还要把对角元规范为首一，并检查逐项整除链。" },
        { question: "λ-矩阵等价与普通矩阵相似的左右因子有何区别？", answer: "等价允许独立的 U、V；相似要求左右因子互为逆并且来自同一个换基矩阵。" },
      ],
      misconceptions: ["把任意多项式倍乘当成可逆操作", "有对角形就停止而不检查整除", "只记操作步骤而忽略次数下降的终止理由"],
      summary: [
        `Smith 化简由可逆行列操作组成，因此全过程保持 λ-矩阵等价。`,
        `欧几里得算法通过严格降低余数次数，保证一般矩阵也能产生 gcd 主元。`,
        `递归清行清列并修正整除关系，最终得到首一且逐项整除的标准形。`,
      ],
      textbook: { reference: sources.polynomial, items: ["多项式矩阵等价", "欧几里得算法", "Smith 标准形存在性"] },
    },
    {
      id: "invariant-factors",
      number: "§3",
      textbookSection: "不变因子",
      title: "不变因子",
      navTitle: "不变因子",
      question: "初等变换会混合大量子式，为什么它们的 gcd 仍能唯一锁定 Smith 对角元？",
      goal: "从全部同阶子式的 gcd 证明 Smith 标准形的唯一性，并把不变因子连接到特征多项式、最小多项式和相似分类。",
      tags: ["行列式因子", "唯一性", "最小多项式"],
      intro:
        `Smith 化简给出了标准形的存在性，还需要证明不同化简路线不会得到不同答案。解决办法是同时观察全部 ${I("k")} 阶子式：初等变换会重新组合它们，却不会改变它们的首一最大公因式。`,
      observe: {
        title: "把许多会变化的量压缩成一个不变量",
        lead: "实验从 Smith 端展示 Δₖ 如何恢复 dₖ；理论模块再沿一次初等变换追踪 gcd 为何保持。",
        cues: [
          `${I("\\Delta_k")} 必须使用全部 ${I("k")} 阶子式。`,
          "一次行倍加会把新的子式写成旧子式的多项式线性组合。",
          "操作可逆，所以变换前后的 gcd 必须互相整除。",
          `${I("d_k=\\Delta_k/\\Delta_{k-1}")} 把累计信息拆成每一层新增的信息。`,
        ],
      },
      interactive: {
        kind: "invariant-story",
        title: "从全部子式恢复唯一对角元",
        description: "逐级收集 1、2、3 阶子式，压缩成 Δ₁、Δ₂、Δ₃，再恢复不变因子并比较同一特征多项式下的两种结构。",
        mission: `解释 ${I("\\Delta_k")} 为什么能够脱离具体化简路线，并用它区分 ${I("2I")} 与二阶 Jordan 块。`,
        steps: [
          { action: "收集", watch: "同一阶的全部子式共同进入 gcd。" },
          { action: "压缩", watch: "Δₖ 保留这一阶所有子式的公共因子。" },
          { action: "相除", watch: "dₖ 是 Δₖ 相对 Δₖ₋₁ 新增加的部分。" },
          { action: "比较", watch: "相同乘积可以来自不同的不变因子链。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "行列式因子来自全部同阶子式",
          subtitle: "先取所有子式，再取首一 gcd。",
          body: `令 ${I("\\Delta_k(M)")} 为 ${I("M(\\lambda)")} 的全部 ${I("k")} 阶子式的首一最大公因式，并约定 ${I("\\Delta_0=1")}。若所有 ${I("k")} 阶子式都为零，则取 ${I("\\Delta_k=0")}。`,
          formula: "\\Delta_k(M)=\\gcd\\{\\det M_{I,J}:|I|=|J|=k\\}.",
        },
        {
          number: "02",
          title: "一次初等变换不会改变 Δₖ",
          subtitle: "线性组合给出一个方向，可逆性给出反方向。",
          body: `行倍加后，每个新的 ${I("k")} 阶子式都是若干旧子式的多项式线性组合，所以旧的 gcd 整除全部新子式。对逆变换重复同一论证，新 gcd 也整除全部旧子式；首一规范后两者相等。交换与常数倍乘同理。`,
        },
        {
          number: "03",
          title: "Smith 对角形的 Δₖ 是前 k 项乘积",
          subtitle: "整除链使最小的非零乘积一眼可见。",
          body: `若 Smith 形的非零对角元满足 ${I("d_1\\mid\\cdots\\mid d_r")}，则全部 ${I("k")} 阶子式的 gcd 为 ${I("d_1d_2\\cdots d_k")}。`,
          formula: "\\Delta_k=d_1d_2\\cdots d_k.",
        },
        {
          number: "04",
          title: "相邻相除得到唯一的不变因子",
          subtitle: "这一步同时证明 Smith 标准形唯一。",
          body: `${I("\\Delta_k")} 只由原矩阵决定，因此 ${I("d_k=\\Delta_k/\\Delta_{k-1}")} 也只由原矩阵决定。任何两条 Smith 化简路线都必须得到同一组首一对角元。`,
          formula: "d_k=\\frac{\\Delta_k}{\\Delta_{k-1}}.",
        },
        {
          number: "05",
          title: "特征矩阵把多项式信息带回 A",
          subtitle: "乘积是特征多项式，末项是最小多项式。",
          body: `对 ${I("\\lambda I-A")}，全部非单位不变因子的乘积等于 ${I("\\chi_A(\\lambda)")}；最后一个非单位不变因子等于 ${I("m_A(\\lambda)")}。前者记录总量，后者记录最大局部复杂度。`,
        },
        {
          number: "06",
          title: "完整链比两个端点更精细",
          subtitle: "相同 χ 和 m 仍可能留下中间层差异。",
          body: `特征多项式只给出全部不变因子的乘积，最小多项式只给出最后一项。矩阵维数较高时，完整的不变因子链才能保留全部相似分类信息。`,
        },
      ],
      example: {
        title: "同一特征多项式怎样分叉成两条链",
        question: `设 ${I("A=2I_2")}，${I("B=\\begin{bmatrix}2&1\\\\0&2\\end{bmatrix}")}。它们的特征矩阵分别具有哪组不变因子？`,
        choices: [
          { text: `两者都是 ${I("\\lambda-2,\\lambda-2")}。`, correct: false },
          { text: `两者都是 ${I("1,(\\lambda-2)^2")}。`, correct: false },
          { text: `${I("A: \\lambda-2,\\lambda-2")}；${I("B:1,(\\lambda-2)^2")}。`, correct: true },
          { text: `${I("A:1,(\\lambda-2)^2")}；${I("B:\\lambda-2,\\lambda-2")}。`, correct: false },
        ],
        steps: [
          `${I("\\lambda I-A=\\operatorname{diag}(\\lambda-2,\\lambda-2)")}，所以 ${I("\\Delta_1=\\lambda-2")}，${I("\\Delta_2=(\\lambda-2)^2")}。`,
          `因此 ${I("A")} 的不变因子为 ${I("\\lambda-2,\\lambda-2")}。`,
          `${I("\\lambda I-B=\\begin{bmatrix}\\lambda-2&-1\\\\0&\\lambda-2\\end{bmatrix}")} 含有常数子式 ${I("-1")}，所以 ${I("\\Delta_1=1")}。`,
          `两阶行列式仍为 ${I("(\\lambda-2)^2")}，故 ${I("B")} 的不变因子为 ${I("1,(\\lambda-2)^2")}。`,
          `两条链的乘积相同，完整链不同，因此两个矩阵不相似。`,
        ],
      },
      quiz: [
        { question: `${I("\\Delta_k")} 为什么必须使用全部 k 阶子式？`, answer: "它要记录所有子式共有的因子；任选一个子式会保留与位置有关的偶然信息。" },
        { question: "证明 Δₖ 不变时，为什么一定要使用逆变换？", answer: "线性组合只给出一个整除方向；逆变换给出反向整除，二者合起来才得到相等。" },
        { question: "怎样由 Δₖ 恢复 dₖ？", answer: `${I("d_k=\\Delta_k/\\Delta_{k-1}")}。` },
        { question: "特征矩阵最后一个非单位不变因子是什么？", answer: "矩阵的最小多项式。" },
      ],
      misconceptions: ["用一个最大的子式代替全部子式的 gcd", "只证明一个整除方向就宣布不变", "把特征多项式与最小多项式当成完整分类数据"],
      summary: [
        `全部同阶子式的首一 gcd 在可逆行列变换下保持不变。`,
        `${I("\\Delta_k=d_1\\cdots d_k")} 使不变因子以及 Smith 标准形都被唯一确定。`,
        `对特征矩阵而言，完整不变因子链保存了判断相似所需的结构信息。`,
      ],
      textbook: { reference: sources.polynomial, items: ["行列式因子", "Smith 唯一性", "特征与最小多项式"] },
    },
    {
      id: "similarity-criterion",
      number: "§4",
      textbookSection: "矩阵相似的条件",
      title: "矩阵相似的条件",
      navTitle: "矩阵相似的条件",
      question: "为什么特征矩阵等价既是相似的必要条件，也是充分条件？",
      goal: "把相似理解为同一算子的换基表示，并用不变因子与有理标准形建立完整的相似判据。",
      tags: ["换基", "充要条件", "分类定理"],
      intro:
        `相似矩阵记录同一个线性算子，只是使用了不同的坐标语言。换基很快给出“相似必然拥有相同不变因子”；反方向需要证明这组不变量能够重建一个共同的标准代表，这项工作将在第 7 节由有理标准形完成。`,
      observe: {
        title: "先固定算子，再比较坐标记录",
        lead: "实验的前半段展示换基的几何含义，后半段逐层检查哪些指标只能排除、哪些指标能够完成分类。",
        cues: [
          "坐标网格与矩阵记录随基改变，向量和线性算子本身保持不变。",
          `${I("B=P^{-1}AP")} 会诱导 ${I("\\lambda I-B=P^{-1}(\\lambda I-A)P")}。`,
          "迹、行列式、特征多项式和最小多项式都可以提供必要条件。",
          "完整不变因子链通过有理标准形给出充分性。",
        ],
      },
      interactive: {
        kind: "similarity-story",
        title: "同一算子的双坐标房间与结构护照",
        description: "保持几何对象不动并连续换基，再逐页比较一对真相似矩阵与一对只有粗指标相同的矩阵。",
        mission: `分别说明“相似推出特征矩阵等价”和“相同不变因子推出相似”需要哪一步理由。`,
        steps: [
          { action: "换基", watch: "对象不动，坐标网格和矩阵记录改变。" },
          { action: "推出必要性", watch: "同一个 P 同时出现在特征矩阵两侧。" },
          { action: "排除伪相似", watch: "粗指标相同仍可能在不变因子层分叉。" },
          { action: "预告充分性", watch: "相同不变因子将在 §7 重建同一个有理标准形。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "相似是同一算子的换基公式",
          subtitle: "P 的列给出新基在旧坐标中的表示。",
          body: `若线性算子在两组基下的矩阵分别为 ${I("A,B")}，过渡矩阵为 ${I("P")}，则 ${I("B=P^{-1}AP")}。矩阵元素会改变，算子的迭代、核与像等结构保持一致。`,
          formula: "B=P^{-1}AP.",
        },
        {
          number: "02",
          title: "相似必然使特征矩阵等价",
          subtitle: "这是完整判据的必要性。",
          body: `由换基公式直接得到 ${I("\\lambda I-B=P^{-1}(\\lambda I-A)P")}。常数可逆矩阵 ${I("P^{-1},P")} 也属于 ${I("GL_n(F[\\lambda])")}，因此两特征矩阵等价并拥有相同不变因子。`,
          formula: "\\lambda I-B=P^{-1}(\\lambda I-A)P.",
        },
        {
          number: "03",
          title: "粗不变量只能逐层排除",
          subtitle: "相等可以继续检查，不等可以立即否定。",
          body: `迹、行列式与特征多项式相同都不能保证相似；最小多项式也只给出最后一个不变因子。它们适合快速排除，完整分类仍需全部不变因子。`,
        },
        {
          number: "04",
          title: "相似判据",
          subtitle: "特征矩阵等价完整刻画普通矩阵相似。",
          body: `同阶矩阵 ${I("A,B")} 相似，当且仅当 ${I("\\lambda I-A")} 与 ${I("\\lambda I-B")} 在 ${I("F[\\lambda]")} 上等价；等价地说，它们的不变因子逐项相同。`,
          formula: "A\\sim B\\Longleftrightarrow \\lambda I-A\\sim_{\\mathrm{eq}}\\lambda I-B.",
        },
        {
          number: "05",
          title: "充分性依靠标准代表",
          subtitle: "§7 将补上这条证明链。",
          body: `相同不变因子 ${I("d_1\\mid\\cdots\\mid d_s")} 会产生同一个伴随块直和 ${I("C(d_1)\\oplus\\cdots\\oplus C(d_s)")}。若 ${I("A,B")} 都相似于这个有理标准形，它们便彼此相似。`,
        },
        {
          number: "06",
          title: "分类定理的含义",
          subtitle: "不变因子既能识别，也能重建。",
          body: `一组真正完整的不变量必须同时做到两件事：相似矩阵得到相同数据；相同数据能够重建同一个标准代表。不变因子通过 Smith 形完成识别，通过有理标准形完成重建。`,
        },
      ],
      example: {
        title: "写出一次真实换基",
        question: `设 ${I("A=\\begin{bmatrix}2&0\\\\0&1\\end{bmatrix}")}，${I("B=\\begin{bmatrix}2&1\\\\0&1\\end{bmatrix}")}。下面哪个矩阵满足 ${I("B=P^{-1}AP")}？`,
        choices: [
          { text: `${I("P=\\begin{bmatrix}1&1\\\\0&1\\end{bmatrix}")}。`, correct: true },
          { text: `${I("P=\\begin{bmatrix}1&0\\\\1&1\\end{bmatrix}")}。`, correct: false },
          { text: `${I("P=\\begin{bmatrix}0&1\\\\1&0\\end{bmatrix}")}。`, correct: false },
          { text: "不存在这样的可逆矩阵。", correct: false },
        ],
        steps: [
          `取 ${I("P=\\begin{bmatrix}1&1\\\\0&1\\end{bmatrix}")}，它的两列可以看成一组新基。`,
          `计算 ${I("AP=\\begin{bmatrix}2&2\\\\0&1\\end{bmatrix}")}。`,
          `同时 ${I("PB=\\begin{bmatrix}2&2\\\\0&1\\end{bmatrix}")}，所以 ${I("AP=PB")}。`,
          `左乘 ${I("P^{-1}")} 得 ${I("B=P^{-1}AP")}。`,
          `因此两矩阵的特征矩阵等价，并具有相同不变因子。`,
        ],
      },
      quiz: [
        { question: "相似变换改变线性算子本身吗？", answer: "不改变；它改变的是同一算子的坐标表示。" },
        { question: "为什么相似一定推出特征矩阵等价？", answer: `${I("\\lambda I-B=P^{-1}(\\lambda I-A)P")}，左右因子在多项式环上可逆。` },
        { question: "最小多项式相同为什么仍可能不够？", answer: "它只确定最后一个不变因子，较高维时中间不变因子仍可能不同。" },
        { question: "相同不变因子怎样推出相似？", answer: "它们产生同一个有理标准形，两个矩阵都与该标准形相似。" },
      ],
      misconceptions: ["把换基理解成改变线性算子", "把必要条件反向使用", "陈述充分性却省略标准形的重建桥梁"],
      summary: [
        `相似是同一个线性算子在不同基下的矩阵记录。`,
        `相似使特征矩阵等价，所以全部不变因子都保持不变。`,
        `反方向由有理标准形完成：相同不变因子重建同一个标准代表。`,
      ],
      textbook: { reference: sources.similarity, items: ["换基与相似", "特征矩阵等价", "完整相似判据"] },
    },
    {
      id: "elementary-divisors",
      number: "§5",
      textbookSection: "初等因子",
      title: "初等因子",
      navTitle: "初等因子",
      question: "怎样把不变因子的整除链拆成局部幂块，并在不丢信息的前提下重新拼回去？",
      goal: "理解初等因子的底域依赖与局部结构，并掌握不变因子和初等因子之间可逆的右对齐重组方法。",
      tags: ["不可约幂", "右对齐", "局部结构"],
      intro:
        `不变因子把信息按整除层组织，初等因子把同一信息按不可约多项式族组织。两种排列就像同一张表的行视图和列视图：因子族决定列，指数决定高度，右对齐使整除链能够唯一恢复。`,
      observe: {
        title: "颜色跟随因子族，高度跟随指数",
        lead: "实验先改变底域，再拆分和重组。每次操作都要同时追踪不可约性、指数和所在层。",
        cues: [
          "先固定底域，再谈不可约分解。",
          `每个 ${I("p(\\lambda)^e")} 单独成为一个初等因子。`,
          "同一不可约因子族的指数按从小到大排列。",
          "不同族右对齐后逐列相乘，恢复逐项整除的不变因子。",
        ],
      },
      interactive: {
        kind: "elementary-story",
        title: "初等因子的分族与重组",
        description: `在 ${I("\\mathbb R")} 与 ${I("\\mathbb C")} 之间切换，观察 ${I("\\lambda^2+1")} 的分裂，再把幂块按族重排。`,
        mission: `说明底域为什么会改变初等因子，并用“同族排序、右端对齐、逐列相乘”解释怎样恢复不变因子链。`,
        steps: [
          { action: "固定底域", watch: "不可约多项式族随底域改变。" },
          { action: "拆成幂块", watch: "每个初等因子只含一个不可约因子族。" },
          { action: "同族排序", watch: "指数从小到大排列，幂次由高度表达。" },
          { action: "右对齐重组", watch: "逐列相乘后自动得到整除链。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "初等因子是单个不可约多项式的幂",
          subtitle: "把每个不变因子做唯一因式分解。",
          body: `若 ${I("d_i=\\prod_p p(\\lambda)^{e_{p,i}}")}，其中 ${I("p")} 为首一不可约多项式，则所有指数大于零的 ${I("p^{e_{p,i}}")} 构成初等因子多重集。重复出现的幂块必须全部保留。`,
        },
        {
          number: "02",
          title: "底域决定不可约因子族",
          subtitle: "改变底域会重新划分局部结构。",
          body: `${I("\\lambda^2+1")} 在 ${I("\\mathbb R")} 上不可约；在 ${I("\\mathbb C")} 上分解为 ${I("(\\lambda-i)(\\lambda+i)")}。因此初等因子必须与底域一起陈述。`,
        },
        {
          number: "03",
          title: "从不变因子到初等因子只需逐项分解",
          subtitle: "整除链保证每个因子族的指数不会下降。",
          body: `由 ${I("d_1\\mid\\cdots\\mid d_s")} 可知，对每个固定的不可约 ${I("p")}，指数序列 ${I("e_{p,1}\\le\\cdots\\le e_{p,s}")} 单调不减。删去其中的零指数便得到该族的全部初等因子。`,
        },
        {
          number: "04",
          title: "从初等因子恢复不变因子要右对齐",
          subtitle: "较短的因子族在左侧补零指数。",
          body: `把每个不可约因子族的指数从小到大写成一行，再把各行的末端对齐。对齐后的每一列相乘得到一个 ${I("d_i")}。右侧列指数逐项不小于左侧列，因此自动满足整除链。`,
          formula: "d_i(\\lambda)=\\prod_p p(\\lambda)^{e_{p,i}}.",
        },
        {
          number: "05",
          title: "两套数据包含完全相同的信息",
          subtitle: "整除层适合有理标准形，局部幂块适合 Jordan 分析。",
          body: `不变因子突出不同循环块之间的整除顺序；初等因子突出每个不可约因子对应的局部块。唯一因式分解和右对齐规则使两者能够互相恢复。`,
        },
        {
          number: "06",
          title: "线性因子的幂就是 Jordan 块的尺寸",
          subtitle: "这条对应只在多项式已经分裂时成立。",
          body: `若底域中 ${I("p(\\lambda)=\\lambda-\\lambda_0")}，初等因子 ${I("(\\lambda-\\lambda_0)^e")} 对应一个 ${I("e")} 阶 Jordan 块。高次不可约因子则保留在有理标准块中。`,
        },
      ],
      example: {
        title: "用右对齐从初等因子恢复整除链",
        question: `在 ${I("\\mathbb R")} 上，初等因子为 ${I("\\lambda-1")}、${I("(\\lambda-1)^3")}、${I("(\\lambda^2+1)^2")}。对应的不变因子是什么？`,
        choices: [
          { text: `${I("d_1=\\lambda-1,\\ d_2=(\\lambda-1)^3(\\lambda^2+1)^2")}。`, correct: true },
          { text: `${I("d_1=(\\lambda-1)(\\lambda^2+1)^2,\\ d_2=(\\lambda-1)^3")}。`, correct: false },
          { text: `三个初等因子分别就是三个不变因子。`, correct: false },
          { text: `${I("d_1=(\\lambda-1)^4,\\ d_2=(\\lambda^2+1)^2")}。`, correct: false },
        ],
        steps: [
          `${I("\\lambda-1")} 族的指数为 ${I("1,3")}，共有两列。`,
          `${I("\\lambda^2+1")} 族只有指数 ${I("2")}，右对齐后写成 ${I("0,2")}。`,
          `第一列相乘得到 ${I("d_1=(\\lambda-1)^1")}。`,
          `第二列相乘得到 ${I("d_2=(\\lambda-1)^3(\\lambda^2+1)^2")}。`,
          `检查 ${I("d_1\\mid d_2")}，所有初等因子也都恰好出现一次。`,
        ],
      },
      quiz: [
        { question: "初等因子能否含有两个不同不可约多项式？", answer: "不能；它必须是一个首一不可约多项式的正整数幂。" },
        { question: "为什么改变底域可能改变初等因子？", answer: "同一个多项式在不同域上的不可约分解可能不同。" },
        { question: "重组不变因子时为什么要右对齐？", answer: "右对齐让每个因子族的指数逐列不减，从而保证相邻不变因子的整除关系。" },
        { question: `${I("(\\lambda-2)^3")} 在分裂域中对应什么？`, answer: "一个特征值为 2、大小为 3 的 Jordan 块。" },
      ],
      misconceptions: ["离开底域讨论不可约性", "合并或遗漏重复初等因子", "按任意顺序拼接而不检查右对齐与整除链"],
      summary: [
        `初等因子把完整不变因子链拆成按不可约多项式分族的幂块。`,
        `同族指数排序并右对齐后逐列相乘，可以唯一恢复不变因子。`,
        `在分裂域中，线性初等因子的指数直接给出 Jordan 块大小。`,
      ],
      textbook: { reference: `${sources.polynomial}；${sources.jordan}`, items: ["初等因子", "底域与不可约分解", "初等因子和 Jordan 块"] },
    },
    {
      id: "jordan-derivation",
      number: "§6",
      textbookSection: "若尔当标准形的理论推导",
      title: "若尔当标准形的理论推导",
      navTitle: "若尔当标准形推导",
      question: "广义特征向量链为什么一定能补成一组基？核增长又怎样证明 Jordan 块唯一？",
      goal: "从广义特征空间分解和幂零算子的链基定理建立 Jordan 形的存在性，再用高次核的增长恢复块的数量与大小。",
      tags: ["广义特征空间", "链基存在性", "核增长"],
      intro:
        `特征多项式在底域上完全分裂时，空间可按特征值分成若干广义特征空间。在其中固定 ${I("\\lambda_0")} 并令 ${I("N=A-\\lambda_0I")}，问题就变成：怎样为幂零算子寻找一组由向量链组成的基。链基给出 Jordan 形的存在性，核维数序列给出它的唯一性。`,
      observe: {
        title: "把存在性和读取规则分成两步",
        lead: "实验展示已建成链塔后怎样读取块；理论模块补足这些链为什么能够覆盖整个广义特征空间。",
        cues: [
          `${I("\\ker N\\subseteq\\ker N^2\\subseteq\\cdots")} 最终停止增长。`,
          `链 ${I("Nv_1=0,\\ Nv_2=v_1,\\ldots")} 给出一个 Jordan 块。`,
          "幂零算子的链基定理保证可以用若干条链覆盖整个空间。",
          `${I("\\dim\\ker N^k-\\dim\\ker N^{k-1}")} 等于长度至少为 ${I("k")} 的链数。`,
        ],
      },
      interactive: {
        kind: "jordan-story",
        title: "Jordan 链塔与核增长阶梯",
        description: "搭出长度 3 和长度 2 的链塔，再从 ker N、ker N²、ker N³ 的增长反向恢复两座塔。",
        mission: `说明链塔证明了什么、核增长又证明了什么，并仅根据 ${I("0,2,4,5")} 恢复全部 Jordan 块。`,
        steps: [
          { action: "搭链底", watch: "ker N 的维数给出链的总数。" },
          { action: "延长链", watch: "每个高层向量在 N 作用下落到下一层。" },
          { action: "读取横截面", watch: "第 k 次增长统计仍能延伸到第 k 层的链。" },
          { action: "恢复块", watch: "增长量的相邻差给出恰好为各尺寸的块数。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "高次核最终稳定",
          subtitle: "有限维性限制了严格增长的次数。",
          body: `对 ${I("T=A-\\lambda_0I")}，有 ${I("\\ker T^0\\subseteq\\ker T\\subseteq\\ker T^2\\subseteq\\cdots")}。一旦相邻两项相等，后面各项都相等；最迟在 ${I("n=\\dim V")} 次幂处稳定。`,
          formula: "\\ker T^n=\\ker T^{n+1}=\\cdots.",
        },
        {
          number: "02",
          title: "广义特征空间补足缺失的特征向量",
          subtitle: "普通特征空间只是增长链的第一层。",
          body: `定义 ${I("G_{\\lambda_0}=\\ker(A-\\lambda_0I)^n")}。若特征多项式在 ${I("F")} 上完全分裂，不同特征值的广义特征空间组成直和，并覆盖整个空间。`,
          formula: "V=\\bigoplus_{\\lambda\\in\\sigma(A)}G_\\lambda.",
        },
        {
          number: "03",
          title: "每个广义特征空间上只剩一个幂零问题",
          subtitle: "把特征值部分 λ₀I 暂时移开。",
          body: `在 ${I("G_{\\lambda_0}")} 上，${I("N=A-\\lambda_0I")} 是幂零算子。若能找到 ${I("N")} 的链基，那么加回 ${I("\\lambda_0I")} 后，每条链就变成一个 Jordan 块。`,
        },
        {
          number: "04",
          title: "幂零算子一定存在链基",
          subtitle: "对像空间归纳，再把链向上提升。",
          body: `对 ${I("\\dim V")} 归纳。在 ${I("\\operatorname{range}N")} 上先取得链基；为每条链的顶端选择一个原像，把链向上延长一层；最后用 ${I("\\ker N")} 中尚未覆盖的向量补成长度 1 的链。对最高次幂逐层作用即可验证所得向量线性无关并张成 ${I("V")}。`,
        },
        {
          number: "05",
          title: "一条链给出一个 Jordan 块",
          subtitle: "超对角线上的 1 来自向下移动关系。",
          body: `若 ${I("Nv_1=0")} 且 ${I("Nv_j=v_{j-1}\\ (j\\ge2)")}，在有序基 ${I("v_1,\\ldots,v_s")} 下，${I("N")} 的矩阵是幂零 Jordan 块；${I("A=\\lambda_0I+N")} 的矩阵就是 ${I("J_s(\\lambda_0)")}。`,
        },
        {
          number: "06",
          title: "核增长量统计至少达到某层的块",
          subtitle: "每个 k 阶以上的块向 ker Nᵏ 贡献一个新维度。",
          body: `令 ${I("\\nu_k=\\dim\\ker N^k")} 且 ${I("\\nu_0=0")}。则 ${I("b_k=\\nu_k-\\nu_{k-1}")} 等于大小至少为 ${I("k")} 的 Jordan 块个数。`,
          formula: "b_k=\\nu_k-\\nu_{k-1}.",
        },
        {
          number: "07",
          title: "相邻增长量确定精确块数",
          subtitle: "存在性来自链基，唯一性来自核维数。",
          body: `大小恰好为 ${I("k")} 的块数为 ${I("b_k-b_{k+1}")}，也就是 ${I("2\\nu_k-\\nu_{k-1}-\\nu_{k+1}")}。这些维数在相似下保持不变，因此 Jordan 块的尺寸与数量唯一。`,
        },
      ],
      example: {
        title: "由核增长恢复全部 Jordan 块",
        question: `对某个特征值，已知 ${I("\\nu_0=0,\\nu_1=2,\\nu_2=4,\\nu_3=5")}，且以后不再增长。Jordan 块大小是什么？`,
        choices: [
          { text: "一个 5 阶块。", correct: false },
          { text: "两个块，大小为 3 和 2。", correct: true },
          { text: "三个块，大小为 2、2、1。", correct: false },
          { text: "两个块，大小都为 2。", correct: false },
        ],
        steps: [
          `${I("b_1=\\nu_1-\\nu_0=2")}，所以共有两条链。`,
          `${I("b_2=\\nu_2-\\nu_1=2")}，两条链长度都至少为 2。`,
          `${I("b_3=\\nu_3-\\nu_2=1")}，只有一条链长度至少为 3。`,
          `以后不再增长，说明 ${I("b_4=0")}，没有长度至少为 4 的链。`,
          `因此精确块数为一个 3 阶块和一个 2 阶块。`,
        ],
      },
      quiz: [
        { question: "为什么高次核一旦停止增长就不会再次增长？", answer: `若 ${I("\\ker T^m=\\ker T^{m+1}")}，对更高次核中的向量逐次应用 T，可把包含关系反推回该等式。` },
        { question: "Jordan 链存在性的核心定理是什么？", answer: "每个有限维幂零算子都存在由若干条广义特征向量链组成的基。" },
        { question: `${I("\\dim\\ker N")} 表示什么？`, answer: "对应特征值的 Jordan 块总数，也就是该特征值的几何重数。" },
        { question: "Jordan 标准形在什么底域条件下存在？", answer: "特征多项式需要在该底域上完全分裂。" },
      ],
      misconceptions: ["看到链图就默认链基已经存在", "把普通特征空间当成整个广义特征空间", "只用代数重数猜测 Jordan 块"],
      summary: [
        `完全分裂时，空间先分解为广义特征空间，每个分量化成一个幂零算子问题。`,
        `幂零算子的链基定理给出 Jordan 形的存在性，链关系产生块中的超对角线 1。`,
        `高次核维数的增长唯一确定链数和链长，从而确定 Jordan 形。`,
      ],
      textbook: { reference: sources.jordan, items: ["广义特征空间", "幂零算子的链基", "核增长与 Jordan 唯一性"] },
    },
    {
      id: "rational-canonical-form",
      number: "§7",
      textbookSection: "矩阵的有理标准形",
      title: "矩阵的有理标准形",
      navTitle: "有理标准形",
      question: "一条向量轨道只描述一个循环子空间，怎样把全空间分解成唯一的伴随块直和？",
      goal: "从向量消去多项式与循环子空间建立伴随矩阵，再用循环分解定理构造任意域上的有理标准形并完成相似判据。",
      tags: ["消去多项式", "循环分解", "伴随块"],
      intro:
        `从 ${I("v,Av,A^2v,\\ldots")} 出发，第一次线性相关给出只作用于 ${I("v")} 的最小消去多项式，并把这一条轨道写成伴随矩阵。全空间还需要循环分解定理：选择若干条合适轨道组成直和，并让它们的消去多项式形成不变因子整除链。`,
      observe: {
        title: "先完成一个循环块，再追问全空间怎样拼接",
        lead: "实验清楚展示移位与反馈；理论模块负责说明哪些轨道能够组成规范的全空间分解。",
        cues: [
          `只要 ${I("v,Av,\\ldots,A^{r-1}v")} 独立，它们就形成循环子空间中的自然基。`,
          `第一次关系 ${I("p_v(A)v=0")} 给出向量 ${I("v")} 的消去多项式。`,
          "一个任意向量只产生局部循环块，全空间需要循环直和分解。",
          "规范分解中的消去多项式正是不变因子，因此伴随块直和唯一。",
        ],
      },
      interactive: {
        kind: "rational-story",
        title: "Krylov 传送带、反馈与伴随块",
        description: `逐次生成 ${I("v,Av,A^2v,A^3v")}，把第一次回流关系写入伴随矩阵，再观察多个规范循环块怎样直和。`,
        mission: `区分“一个向量的回流多项式”和“全空间的不变因子”，并说明循环分解怎样把前者组织成唯一的有理标准形。`,
        steps: [
          { action: "生成轨道", watch: "独立向量不断扩张一个 A-不变循环子空间。" },
          { action: "发现首次回流", watch: "最低次数关系给出 pᵥ，而非自动给出全空间最小多项式。" },
          { action: "写入伴随块", watch: "前列负责移位，末列记录反馈系数。" },
          { action: "规范拼接", watch: "循环分解选择的块按不变因子整除链排列。" },
        ],
      },
      foundation: [
        {
          number: "01",
          title: "一个向量生成一个循环子空间",
          subtitle: "沿着 A 的作用收集这个向量的全部未来。",
          body: `定义 ${I("K(A,v)=\\operatorname{span}\\{v,Av,A^2v,\\ldots\\}")}。它在 ${I("A")} 下保持不变。若第一次相关发生在 ${I("A^rv")}，前 ${I("r")} 个向量构成 ${I("K(A,v)")} 的一组基。`,
        },
        {
          number: "02",
          title: "首次线性关系给出向量消去多项式",
          subtitle: "最低次数与首一规范保证唯一。",
          body: `若 ${I("A^rv=-a_0v-\\cdots-a_{r-1}A^{r-1}v")} 首次成立，则 ${I("p_v(t)=t^r+a_{r-1}t^{r-1}+\\cdots+a_0")} 是满足 ${I("p_v(A)v=0")} 的唯一最低次数首一多项式。`,
          formula: "p_v(A)v=0.",
        },
        {
          number: "03",
          title: "循环基把作用写成伴随矩阵",
          subtitle: "移位列加一列反馈。",
          body: `在基 ${I("v,Av,\\ldots,A^{r-1}v")} 下，${I("A|_{K(A,v)}")} 的矩阵是 ${I("C(p_v)")}。这个循环块的特征多项式和最小多项式都等于 ${I("p_v")}。`,
        },
        {
          number: "04",
          title: "一条任意轨道只给出局部信息",
          subtitle: "pᵥ 一般只是全局最小多项式的因子。",
          body: `${I("p_v")} 消去向量 ${I("v")} 以及它生成的循环子空间；它不必消去全空间中的其他向量。全局最小多项式是所有向量消去多项式的最小公倍数。`,
        },
        {
          number: "05",
          title: "循环分解定理选择规范的若干条轨道",
          subtitle: "存在性与整除链同时出现。",
          body: `存在向量 ${I("v_1,\\ldots,v_s")}，使 ${I("V=K(A,v_1)\\oplus\\cdots\\oplus K(A,v_s)")}；它们的消去多项式可以排列为 ${I("d_1\\mid\\cdots\\mid d_s")}。这些 ${I("d_i")} 正是 ${I("\\lambda I-A")} 的非单位不变因子。`,
          formula: "V=\\bigoplus_{i=1}^s K(A,v_i).",
        },
        {
          number: "06",
          title: "有理标准形是规范循环块的直和",
          subtitle: "它直接由多项式系数构造。",
          body: `把每个循环基依次连接，${I("A")} 的矩阵成为 ${I("C(d_1)\\oplus\\cdots\\oplus C(d_s)")}。不变因子唯一，因此这个块直和除块的固定排列外也是唯一的。`,
          formula: "R_A=C(d_1)\\oplus\\cdots\\oplus C(d_s).",
        },
        {
          number: "07",
          title: "任意域上都能建立有理标准形",
          subtitle: "构造只使用系数，不要求求根。",
          body: `伴随矩阵由 ${I("d_i")} 的系数写出，所以多项式是否分裂都不影响构造。“有理标准形”也不表示底域必须是 ${I("\\mathbb Q")}；它适用于任意给定的域。`,
        },
        {
          number: "08",
          title: "这里完成相似判据的充分性",
          subtitle: "Smith 数据与标准代表终于闭合。",
          body: `若 ${I("\\lambda I-A")} 与 ${I("\\lambda I-B")} 等价，它们具有相同不变因子，因而具有同一个有理标准形 ${I("R")}。于是 ${I("A\\sim R")} 且 ${I("B\\sim R")}，所以 ${I("A\\sim B")}。`,
        },
      ],
      example: {
        title: "由首次回流写出伴随矩阵",
        question: `在基 ${I("v,Av,A^2v")} 下，若首次有 ${I("A^3v=-v+2Av")}，${I("A|_{K(A,v)}")} 的矩阵是什么？`,
        choices: [
          { text: `${I("\\begin{bmatrix}0&0&-1\\\\1&0&2\\\\0&1&0\\end{bmatrix}")}。`, correct: true },
          { text: `${I("\\begin{bmatrix}0&1&0\\\\0&0&1\\\\-1&2&0\\end{bmatrix}")}。`, correct: false },
          { text: `${I("\\begin{bmatrix}0&0&1\\\\1&0&-2\\\\0&1&0\\end{bmatrix}")}。`, correct: false },
          { text: `${I("\\operatorname{diag}(1,-2,1)")}。`, correct: false },
        ],
        steps: [
          `${I("A(v)=Av")} 给出第一列 ${I("(0,1,0)^T")}。`,
          `${I("A(Av)=A^2v")} 给出第二列 ${I("(0,0,1)^T")}。`,
          `${I("A(A^2v)=A^3v=-v+2Av")} 给出第三列 ${I("(-1,2,0)^T")}。`,
          `所以矩阵为 ${I("\\begin{bmatrix}0&0&-1\\\\1&0&2\\\\0&1&0\\end{bmatrix}")}。`,
          `向量消去多项式为 ${I("p_v(t)=t^3-2t+1")}；它描述当前循环子空间，只有当该子空间等于全空间时才同时是整个 A 的最小多项式。`,
        ],
      },
      quiz: [
        { question: "什么是向量 v 的消去多项式？", answer: `满足 ${I("p_v(A)v=0")} 的唯一最低次数首一多项式。` },
        { question: "为什么一条任意 Krylov 轨道通常不足以给出有理标准形？", answer: "它只描述一个循环子空间；全空间可能需要若干个循环子空间的直和。" },
        { question: "规范循环分解中的消去多项式是什么？", answer: "特征矩阵的非单位不变因子，并按逐项整除排列。" },
        { question: "有理标准形怎样完成相似判据？", answer: "相同不变因子产生同一个伴随块直和，因此两个矩阵相似于同一标准代表。" },
      ],
      misconceptions: ["把任意向量的 pᵥ 直接当成全局最小多项式", "从一个循环块直接跳到全空间", "认为有理标准形只适用于有理数域"],
      summary: [
        `一条 Krylov 轨道的首次回流产生向量消去多项式和一个伴随矩阵块。`,
        `循环分解定理把全空间写成规范循环子空间直和，其消去多项式正是不变因子。`,
        `伴随块直和在任意域上给出有理标准形，并闭合特征矩阵等价与普通矩阵相似的充要关系。`,
      ],
      textbook: { reference: sources.rational, items: ["向量消去多项式", "循环分解定理", "有理标准形", "相似判据充分性"] },
    },
  ];

  registerAlgebraChapter({
    id: "ch8",
    icon: "8",
    title: "第八章 λ-矩阵",
    subtitle: "等价 · 不变量 · 标准形",
    summary:
      "本章围绕一个分类问题展开：把 A 提升为特征矩阵 λI−A，用 Smith 标准形提取唯一的不变因子；同一组数据随后按不可约幂组织成初等因子，按循环子空间组织成有理标准形，并在多项式分裂时组织成 Jordan 标准形。",
    sections,
  });
})();
